CREATE TABLE premium_calculation(
   id                                   BIGSERIAL NOT NULL,
   insurance_type_id                    INT,
   xp1                                  VARCHAR(100),
   xp2                                  VARCHAR(100),
   xp3                                  VARCHAR(100),
   xp4                                  VARCHAR(100),
   xp5                                  BOOLEAN,
   xp6                                  BOOLEAN,
   xp7                                  BOOLEAN,
   xp8                                  BOOLEAN,
   xp9                                  text[],
   xp10                                 text[],
   xp11                                 text[],
   xp12                                 text[],
   xp13                                 DECIMAL,
   xp14                                 DECIMAL,
   xp15                                 DECIMAL,
   xp16                                 DECIMAL,
   xp17                                 DATE,
   xp18                                 DATE,
   xp19                                 DATE,
   xp20                                 DATE
 );
