CREATE TABLE country(
   id             BIGSERIAL NOT NULL,
   country_name   VARCHAR(70) NOT NULL,
   country_code   VARCHAR(10) NOT NULL,
   currency_name  VARCHAR(50) NOT NULL,
   currency_code  VARCHAR(10) NOT NULL,
   language_code  text[]
 );
 INSERT INTO country (
 country_name,
 country_code,
 currency_name,
 currency_code,
 language_code ) VALUES
 ('ANDORRA','AD','Euro','EUR','{"ca"}'),
 ('THE UNITED ARAB EMIRATES','AE','UAE Dirham','AED','{"ar"}'),
 ('AFGHANISTAN','AF','Afghani','AFN','{"fa","ps"}'),
 ('ARGENTINA','AG','Argentine Peso','ARS','{"en"}'),
 ('ANGUILLA','AI','East Caribbean Dollar','XCD','{"en"}'),
 ('ALBANIA','AL','Lek','ALL','{"sq"}'),
 ('ARUBA','AM','Aruban Florin','AWG','{"hy"}'),
 ('ANGOLA','AO','Kwanza','AOA','{"pt"}'),
 ('ANTIGUA AND BARBUDA','AQ','East Caribbean Dollar','XCD','{"es"}'),
 ('ARMENIA','AR','Armenian Dram','AMD','{"en", "sm"}'),
 ('AMERICAN SAMOA','AS','US Dollar','USD','{"de"}'),
 ('AZERBAIJAN','AT','Azerbaijanian Manat','AZN','{"en"}'),
 ('AUSTRIA','AU','Euro','EUR','{"nl", "pap"}'),
 ('AUSTRALIA','AW','Australian Dollar','AUD','{"sv"}'),
 ('ÅLAND ISLANDS','AX','Euro','EUR','{"az"}'),
 ('THE BAHAMAS','AZ','Bahamian Dollar','BSD','{"bs", "hr", "sr"}'),
 ('BOSNIA AND HERZEGOVINA','BA','Convertible Mark','BAM','{"en"}'),
 ('BELARUS','BB','Belarussian Ruble','BYN','{"bn"}'),
 ('BARBADOS','BD','Barbados Dollar','BBD','{"nl", "fr", "de"}'),
 ('BELIZE','BE','Belize Dollar','BZD','{"fr"}'),
 ('BURKINA FASO','BF','CFA Franc BCEAO','XOF','{"bg"}'),
 ('BULGARIA','BG','Bulgarian Lev','BGN','{"ar"}'),
 ('BANGLADESH','BH','Taka','BDT','{"fr"}'),
 ('BURUNDI','BI','Burundi Franc','BIF','{"fr"}'),
 ('BERMUDA','BJ','Bermudian Dollar','BMD','{"fr"}'),
 ('SAINT BARTHÉLEMY','BL','Euro','EUR','{"en"}'),
 ('BHUTAN','BM','Indian Rupee','INR','{"ms"}'),
 ('BRUNEI DARUSSALAM','BN','Brunei Dollar','BND','{"es", "qu", "gn", "ay"}'),
 ('BOLIVIA (PLURINATIONAL STATE OF)','BO','Boliviano','BOB','{"nl"}'),
 ('BONAIRE, SINT EUSTATIUS AND SABA','BQ','US Dollar','USD','{"pt"}'),
 ('BRAZIL','BR','Brazilian Real','BRL','{"en"}'),
 ('BAHRAIN','BS','Bahraini Dinar','BHD','{"dz"}'),
 ('BOUVET ISLAND','BV','Norwegian Krone','NOK','{"no"}'),
 ('BOTSWANA','BW','Pula','BWP','{"en", "tn"}'),
 ('BELGIUM','BY','Euro','EUR','{"be", "ru"}'),
 ('BENIN','BZ','CFA Franc BCEAO','XOF','{"en"}'),
 ('CANADA','CA','Canadian Dollar','CAD','{"en", "fr"}'),
 ('THE COCOS (KEELING) ISLANDS','CC','Australian Dollar','AUD','{"en"}'),
 ('CONGO (THE DEMOCRATIC REPUBLIC OF THE)','CD','Congolese Franc','CDF','{"fr"}'),
 ('THE CENTRAL AFRICAN REPUBLIC','CF','CFA Franc BEAC','XAF','{"fr", "sg"}'),
 ('THE CONGO','CG','CFA Franc BEAC','XAF','{"fr"}'),
 ('SWITZERLAND','CH','WIR Franc','CHW','{"de", "fr", "it", "rm"}'),
 ('CÔTE D''IVOIRE','CI','CFA Franc BCEAO','XOF','{"fr"}'),
 ('THE COOK ISLANDS','CK','New Zealand Dollar','NZD','{"en", "rar"}'),
 ('CHILE','CL','Chilean Peso','CLP','{"es"}'),
 ('CAMEROON','CM','CFA Franc BEAC','XAF','{"fr", "en"}'),
 ('CHINA','CN','Yuan Renminbi','CNY','{"zh-hans"}'),
 ('COLOMBIA','CO','Unidad de Valor Real','COU','{"es"}'),
 ('COSTA RICA','CR','Costa Rican Colon','CRC','{"es"}'),
 ('CUBA','CU','Cuban Peso','CUP','{"es"}'),
 ('CABO VERDE','CV','Cabo Verde Escudo','CVE','{"pt"}'),
 ('CURAÇAO','CW','Netherlands Antillean Guilder','ANG','{"nl", "en"}'),
 ('CHRISTMAS ISLAND','CX','Australian Dollar','AUD','{"en"}'),
 ('CYPRUS','CY','Euro','EUR','{"el", "tr"}'),
 ('THE CZECH REPUBLIC','CZ','Czech Koruna','CZK','{"cs"}'),
 ('GERMANY','DE','Euro','EUR','{"de"}'),
 ('DJIBOUTI','DJ','Djibouti Franc','DJF','{"fr", "ar", "so", "aa"}'),
 ('DENMARK','DK','Danish Krone','DKK','{"da"}'),
 ('DOMINICA','DM','East Caribbean Dollar','XCD','{"en"}'),
 ('THE DOMINICAN REPUBLIC','DO','Dominican Peso','DOP','{"es"}'),
 ('ALGERIA','DZ','Algerian Dinar','DZD','{"ar"}'),
 ('ECUADOR','EC','US Dollar','USD','{"es"}'),
 ('ESTONIA','EE','Euro','EUR','{"et"}'),
 ('EGYPT','EG','Egyptian Pound','EGP','{"ar"}'),
 ('WESTERN SAHARA','EH','Moroccan Dirham','MAD','{"ar", "es", "fr"}'),
 ('ERITREA','ER','Nakfa','ERN','{"ti", "ar", "en"}'),
 ('SRI LANKA','ES','Sri Lanka Rupee','LKR','{"ast", "ca", "es", "eu", "gl"}'),
 ('EUROPEAN UNION','ET','Euro','EUR','{"am", "om"}'),
 ('FINLAND','FI','Euro','EUR','{"fi", "sv", "se"}'),
 ('FIJI','FJ','Fiji Dollar','FJD','{"en"}'),
 ('THE FALKLAND ISLANDS [MALVINAS]','FK','Falkland Islands Pound','FKP','{"en"}'),
 ('MEXICO','FM','Mexican Unidad de Inversion (UDI)','MXV','{"en"}'),
 ('THE FAROE ISLANDS','FO','Danish Krone','DKK','{"fo", "da"}'),
 ('FRANCE','FR','Euro','EUR','{"fr"}'),
 ('GABON','GA','CFA Franc BEAC','XAF','{"fr"}'),
 ('THE UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND','GB','Pound Sterling','GBP','{"en", "ga", "cy", "gd", "kw"}'),
 ('GRENADA','GD','East Caribbean Dollar','XCD','{"en"}'),
 ('GEORGIA','GE','Lari','GEL','{"ka"}'),
 ('FRENCH GUIANA','GF','Euro','EUR','{"fr"}'),
 ('GUERNSEY','GG','Pound Sterling','GBP','{"en"}'),
 ('GHANA','GH','Ghana Cedi','GHS','{"en"}'),
 ('GIBRALTAR','GI','Gibraltar Pound','GIP','{"en"}'),
 ('GREENLAND','GL','Danish Krone','DKK','{"kl", "da"}'),
 ('THE GAMBIA','GM','Dalasi','GMD','{"en"}'),
 ('GUINEA','GN','Guinea Franc','GNF','{"fr"}'),
 ('GUADELOUPE','GP','Euro','EUR','{"fr"}'),
 ('EQUATORIAL GUINEA','GQ','CFA Franc BEAC','XAF','{"es", "fr", "pt"}'),
 ('GREECE','GR','Euro','EUR','{"el"}'),
 ('SOUTH AFRICA','GS','Rand','ZAR','{"en"}'),
 ('GUATEMALA','GT','Quetzal','GTQ','{"es"}'),
 ('GUAM','GU','US Dollar','USD','{"en", "ch"}'),
 ('GUINEA-BISSAU','GW','CFA Franc BCEAO','XOF','{"pt"}'),
 ('GUYANA','GY','Guyana Dollar','GYD','{"en"}'),
 ('HONG KONG','HK','Hong Kong Dollar','HKD','{"zh-hant", "en"}'),
 ('HEARD ISLAND AND McDONALD ISLANDS','HM','Australian Dollar','AUD','{"en"}'),
 ('HONDURAS','HN','Lempira','HNL','{"es"}'),
 ('CROATIA','HR','Kuna','HRK','{"hr"}'),
 ('HAITI','HT','US Dollar','USD','{"fr", "ht"}'),
 ('HUNGARY','HU','Forint','HUF','{"hu"}'),
 ('INDONESIA','ID','Rupiah','IDR','{"id"}'),
 ('IRELAND','IE','Euro','EUR','{"en", "ga"}'),
 ('ISRAEL','IL','New Israeli Sheqel','ILS','{"he"}'),
 ('ISLE OF MAN','IM','Pound Sterling','GBP','{"en"}'),
 ('INDIA','IN','Indian Rupee','INR','{"hi", "en"}'),
 ('THE BRITISH INDIAN OCEAN TERRITORY','IO','US Dollar','USD','{"en"}'),
 ('IRAQ','IQ','Iraqi Dinar','IQD','{"ar", "ku"}'),
 ('IRAN (ISLAMIC REPUBLIC OF)','IR','Iranian Rial','IRR','{"fa"}'),
 ('ICELAND','IS','Iceland Krona','ISK','{"is"}'),
 ('ITALY','IT','Euro','EUR','{"it", "de", "fr"}'),
 ('JERSEY','JE','Pound Sterling','GBP','{"en"}'),
 ('JAMAICA','JM','Jamaican Dollar','JMD','{"en"}'),
 ('JORDAN','JO','Jordanian Dinar','JOD','{"ar"}'),
 ('JAPAN','JP','Yen','JPY','{"ja"}'),
 ('KENYA','KE','Kenyan Shilling','KES','{"sw", "en"}'),
 ('KYRGYZSTAN','KG','Som','KGS','{"ky", "ru"}'),
 ('CAMBODIA','KH','Riel','KHR','{"km"}'),
 ('KIRIBATI','KI','Australian Dollar','AUD','{"en"}'),
 ('THE COMOROS','KM','Comoro Franc','KMF','{"ar", "fr", "sw"}'),
 ('SAINT KITTS AND NEVIS','KN','East Caribbean Dollar','XCD','{"en"}'),
 ('KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)','KP','North Korean Won','KPW','{"ko"}'),
 ('KOREA (THE REPUBLIC OF)','KR','Won','KRW','{"ko", "en"}'),
 ('KUWAIT','KW','Kuwaiti Dinar','KWD','{"ar"}'),
 ('THE CAYMAN ISLANDS','KY','Cayman Islands Dollar','KYD','{"en"}'),
 ('KAZAKHSTAN','KZ','Tenge','KZT','{"kk", "ru"}'),
 ('THE LAO PEOPLE’S DEMOCRATIC REPUBLIC','LA','Kip','LAK','{"lo"}'),
 ('LEBANON','LB','Lebanese Pound','LBP','{"ar", "fr"}'),
 ('SAINT LUCIA','LC','East Caribbean Dollar','XCD','{"en"}'),
 ('LIECHTENSTEIN','LI','Swiss Franc','CHF','{"de"}'),
 ('THE SUDAN','LK','Sudanese Pound','SDG','{"si", "ta"}'),
 ('LIBERIA','LR','Liberian Dollar','LRD','{"en"}'),
 ('LESOTHO','LS','Rand','ZAR','{"en", "st"}'),
 ('LITHUANIA','LT','Euro','EUR','{"lt"}'),
 ('LUXEMBOURG','LU','Euro','EUR','{"lb", "fr", "de"}'),
 ('LATVIA','LV','Euro','EUR','{"lv"}'),
 ('LIBYA','LY','Libyan Dinar','LYD','{"ar"}'),
 ('MONTSERRAT','MA','East Caribbean Dollar','XCD','{"fr", "zgh", "ar"}'),
 ('MOLDOVA (THE REPUBLIC OF)','MC','Moldovan Leu','MDL','{"fr"}'),
 ('MICRONESIA (FEDERATED STATES OF)','MD','US Dollar','USD','{"ro", "ru", "uk"}'),
 ('MONGOLIA','ME','Tugrik','MNT','{"srp","sr", "hr", "bs", "sq"}'),
 ('SAINT MARTIN (FRENCH PART)','MF','Euro','EUR','{"fr"}'),
 ('MADAGASCAR','MG','Malagasy Ariary','MGA','{"mg", "fr"}'),
 ('THE MARSHALL ISLANDS','MH','US Dollar','USD','{"en", "mh"}'),
 ('REPUBLIC OF NORTH MACEDONIA','MK','Denar','MKD','{"mk"}'),
 ('MALI','ML','CFA Franc BCEAO','XOF','{"fr"}'),
 ('MOZAMBIQUE','MM','Mozambique Metical','MZN','{"my"}'),
 ('MONACO','MN','Euro','EUR','{"mn"}'),
 ('MACAO','MO','Pataca','MOP','{"zh-hant", "pt"}'),
 ('NORFOLK ISLAND','MP','Australian Dollar','AUD','{"en", "ch"}'),
 ('MARTINIQUE','MQ','Euro','EUR','{"fr"}'),
 ('MAURITANIA','MR','Ouguiya','MRU','{"ar", "fr"}'),
 ('MONTENEGRO','MS','Euro','EUR','{"en"}'),
 ('MALTA','MT','Euro','EUR','{"mt", "en"}'),
 ('MAURITIUS','MU','Mauritius Rupee','MUR','{"mfe", "fr", "en"}'),
 ('MALDIVES','MV','Rufiyaa','MVR','{"dv"}'),
 ('MALAWI','MW','Kwacha','MWK','{"en", "ny"}'),
 ('MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP','MX','ADB Unit of Account','XUA','{"es"}'),
 ('MALAYSIA','MY','Malaysian Ringgit','MYR','{"ms"}'),
 ('MOROCCO','MZ','Moroccan Dirham','MAD','{"pt"}'),
 ('MYANMAR','NA','Kyat','MMK','{"en", "sf", "de"}'),
 ('THE NETHERLANDS','NC','Euro','EUR','{"fr"}'),
 ('NICARAGUA','NE','Cordoba Oro','NIO','{"fr"}'),
 ('NIUE','NF','New Zealand Dollar','NZD','{"en", "pih"}'),
 ('THE NIGER','NG','CFA Franc BCEAO','XOF','{"en"}'),
 ('NEW ZEALAND','NI','New Zealand Dollar','NZD','{"es"}'),
 ('NEPAL','NL','Nepalese Rupee','NPR','{"nl"}'),
 ('THE NORTHERN MARIANA ISLANDS','NO','US Dollar','USD','{"nb", "nn", "no", "se"}'),
 ('NAURU','NP','Australian Dollar','AUD','{"ne"}'),
 ('NAMIBIA','NR','Rand','ZAR','{"na", "en"}'),
 ('NIGERIA','NU','Naira','NGN','{"niu", "en"}'),
 ('NEW CALEDONIA','NZ','CFP Franc','XPF','{"mi", "en"}'),
 ('NORWAY','OM','Norwegian Krone','NOK','{"ar"}'),
 ('PANAMA','PA','US Dollar','USD','{"es"}'),
 ('PERU','PE','Nuevo Sol','PEN','{"es"}'),
 ('FRENCH POLYNESIA','PF','CFP Franc','XPF','{"fr"}'),
 ('PAPUA NEW GUINEA','PG','Kina','PGK','{"en", "tpi", "ho"}'),
 ('THE PHILIPPINES','PH','Philippine Peso','PHP','{"en", "tl"}'),
 ('OMAN','PK','Rial Omani','OMR','{"en", "ur"}'),
 ('POLAND','PL','Zloty','PLN','{"pl"}'),
 ('SAINT PIERRE AND MIQUELON','PM','Euro','EUR','{"fr"}'),
 ('PITCAIRN','PN','New Zealand Dollar','NZD','{"en", "pih"}'),
 ('PUERTO RICO','PR','US Dollar','USD','{"es", "en"}'),
 ('PALAU','PS','US Dollar','USD','{"ar", "he"}'),
 ('PORTUGAL','PT','Euro','EUR','{"pt"}'),
 ('PAKISTAN','PW','Pakistan Rupee','PKR','{"en", "pau", "ja", "sov", "tox"}'),
 ('PARAGUAY','PY','Guarani','PYG','{"es", "gn"}'),
 ('QATAR','QA','Qatari Rial','QAR','{"ar"}'),
 ('RÉUNION','RE','Euro','EUR','{"fr"}'),
 ('ROMANIA','RO','Romanian Leu','RON','{"ro"}'),
 ('SERBIA','RS','Serbian Dinar','RSD','{"sr", "sr-Latn"}'),
 ('THE RUSSIAN FEDERATION','RU','Russian Ruble','RUB','{"ru"}'),
 ('RWANDA','RW','Rwanda Franc','RWF','{"rw", "fr", "en"}'),
 ('SAUDI ARABIA','SA','Saudi Riyal','SAR','{"ar"}'),
 ('SLOVENIA','SB','Euro','EUR','{"en"}'),
 ('SEYCHELLES','SC','Seychelles Rupee','SCR','{"fr", "en", "crs"}'),
 ('SURINAME','SD','Surinam Dollar','SRD','{"ar", "en"}'),
 ('SWEDEN','SE','Swedish Krona','SEK','{"sv"}'),
 ('SINGAPORE','SG','Singapore Dollar','SGD','{"zh-hans", "en", "ms", "ta"}'),
 ('SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA','SH','Saint Helena Pound','SHP','{"en"}'),
 ('SLOVAKIA','SI','Euro','EUR','{"sl"}'),
 ('SWAZILAND','SJ','Lilangeni','SZL','{"no"}'),
 ('SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"','SK','Sucre','XSU','{"sk"}'),
 ('SIERRA LEONE','SL','Leone','SLL','{"en"}'),
 ('SAN MARINO','SM','Euro','EUR','{"it"}'),
 ('SENEGAL','SN','CFA Franc BCEAO','XOF','{"fr"}'),
 ('SOLOMON ISLANDS','SO','Solomon Islands Dollar','SBD','{"so", "ar"}'),
 ('SVALBARD AND JAN MAYEN','SR','Norwegian Krone','NOK','{"nl"}'),
 ('SPAIN','SS','Euro','EUR','{"pt"}'),
 ('SAO TOME AND PRINCIPE','ST','Dobra','STN','{"en"}'),
 ('EL SALVADOR','SV','US Dollar','USD','{"es"}'),
 ('SINT MAARTEN (DUTCH PART)','SX','Netherlands Antillean Guilder','ANG','{"nl", "en"}'),
 ('SYRIAN ARAB REPUBLIC','SY','Syrian Pound','SYP','{"ar"}'),
 ('ETHIOPIA','SZ','Ethiopian Birr','ETB','{"en", "ss"}'),
 ('THE TURKS AND CAICOS ISLANDS','TC','US Dollar','USD','{"en"}'),
 ('CHAD','TD','CFA Franc BEAC','XAF','{"fr", "ar"}'),
 ('THE FRENCH SOUTHERN TERRITORIES','TF','Euro','EUR','{"fr"}'),
 ('TOGO','TG','CFA Franc BCEAO','XOF','{"fr"}'),
 ('THAILAND','TH','Baht','THB','{"th"}'),
 ('TAJIKISTAN','TJ','Somoni','TJS','{"tg", "ru"}'),
 ('TOKELAU','TK','New Zealand Dollar','NZD','{"tkl", "en", "sm"}'),
 ('TIMOR-LESTE','TL','US Dollar','USD','{"pt", "tet"}'),
 ('TURKMENISTAN','TM','Turkmenistan New Manat','TMT','{"tk"}'),
 ('TUNISIA','TN','Tunisian Dinar','TND','{"ar", "fr"}'),
 ('TONGA','TO','Pa’anga','TOP','{"en"}'),
 ('TURKEY','TR','Turkish Lira','TRY','{"tr"}'),
 ('TRINIDAD AND TOBAGO','TT','Trinidad and Tobago Dollar','TTD','{"en"}'),
 ('TUVALU','TV','Australian Dollar','AUD','{"en"}'),
 ('TAIWAN (PROVINCE OF CHINA)','TW','New Taiwan Dollar','TWD','{"zh-hant"}'),
 ('TANZANIA, UNITED REPUBLIC OF','TZ','Tanzanian Shilling','TZS','{"sw", "en"}'),
 ('UKRAINE','UA','Hryvnia','UAH','{"uk"}'),
 ('UGANDA','UG','Uganda Shilling','UGX','{"en", "sw"}'),
 ('THE UNITED STATES MINOR OUTLYING ISLANDS','UM','US Dollar','USD','{"en"}'),
 ('THE UNITED STATES OF AMERICA','US','US Dollar','USD','{"en"}'),
 ('URUGUAY','UY','Peso Uruguayo','UYU','{"es"}'),
 ('UZBEKISTAN','UZ','Uzbekistan Sum','UZS','{"uz", "kaa"}'),
 ('THE HOLY SEE','VA','Euro','EUR','{"it"}'),
 ('SAINT VINCENT AND THE GRENADINES','VC','East Caribbean Dollar','XCD','{"en"}'),
 ('VENEZUELA (BOLIVARIAN REPUBLIC OF)','VE','Bolivar','VEF','{"es"}'),
 ('VIRGIN ISLANDS (BRITISH)','VG','US Dollar','USD','{"en"}'),
 ('VIRGIN ISLANDS (U.S.)','VI','US Dollar','USD','{"en"}'),
 ('VIET NAM','VN','Dong','VND','{"vi"}'),
 ('VANUATU','VU','Vatu','VUV','{"bi", "en", "fr"}'),
 ('WALLIS AND FUTUNA','WF','CFP Franc','XPF','{"fr"}'),
 ('SAMOA','WS','Tala','WST','{"sm", "en"}'),
 ('YEMEN','YE','Yemeni Rial','YER','{"ar"}'),
 ('MAYOTTE','YT','Euro','EUR','{"fr"}'),
 ('SOMALIA','ZA','Somali Shilling','SOS','{"en", "af", "st", "tn", "xh", "zu"}'),
 ('ZAMBIA','ZM','Zambian Kwacha','ZMW','{"en"}'),
 ('ZIMBABWE','ZW','Zimbabwe Dollar','ZWL','{"en", "sn", "nd"}');
