CREATE TABLE insurance_company(
   id                                   BIGSERIAL NOT NULL,
   registered_company_name              VARCHAR(64) NOT NULL,
   partner_brand_name                   VARCHAR(128),
   company_registration_id              VARCHAR(128) NOT NULL,
   company_vat                          VARCHAR(64),
   website_url                          VARCHAR(255) NOT NULL,
   country_present_in                   VARCHAR(128) NOT NULL,
   state_present_in                     text[],
   select_insurance_product             text[],
   upload_partner_registration_proof    VARCHAR(255) NOT NULL,
   head_sales_name                      VARCHAR(64) NOT NULL,
   head_sales_email                     VARCHAR(100) NOT NULL UNIQUE,
   head_sales_phone                     BIGINT,
   admin_name                           VARCHAR(255) NOT NULL,
   admin_email                          VARCHAR(255) NOT NULL,
   admin_phone                          VARCHAR(255) NOT NULL,
   createdate                           DATE,
   updatedate                           DATE,
   status                               BOOLEAN,
   intermediary_code                    VARCHAR(128),
   intermediary_name                    VARCHAR(128),
   contact                              text[],
   intermediary_address                 VARCHAR(255),
   intermediary_fax                     VARCHAR(128)

);

INSERT INTO insurance_company (
  registered_company_name,
  partner_brand_name,
  company_registration_id,
  company_vat,
  website_url,
  country_present_in,
  state_present_in,
  select_insurance_product,
  upload_partner_registration_proof,
  head_sales_name,
  head_sales_email,
  head_sales_phone,
  admin_name,
  admin_email,
  admin_phone,
  createdate,
  updatedate,
  status,
  intermediary_code,
  intermediary_name,
  contact,
  intermediary_address,
  intermediary_fax ) VALUES
  ('DUMMY DATA XPCOVER',
    'PartnerBrandExample',
    'REG71209323QP',
    'VAT29328922',
    'www.xpcover.com',
    'AMERICA',
    '{"ca", "pk"}',
    '{"2", "3"}',
    'upload/file/patth/293293kwewnaowc',
    'Abhishek',
    'xpcover@test.com',
    3293232030,
    'Abhishek',
    'xpcover@test11.com',
    '3293232030',
    '1999-01-08',
    '1999-01-06',
    true,
    'BR149000',
    'UNISON INS. BROKING SERVICES PVT. LTD',
    '{"2357445", "2325048", "46"}',
    'Palaspa Phata Anupam Narsari Kolkhe Panvel Raigarh',
    'FAX820202WERYU'),

    ('D2UMMY DATA XPCOVER2',
      'PartnerBrandExample2730bcdwhdwjdw',
      'REG712099839233QP',
      'VAT29339382928922',
      'www.Dummyxpcover2.com',
      'INDIA',
      '{"ca", "pk"}',
      '{"12", "3"}',
      'upload/file/patth/2393892hbhbde',
      'Sinha Abhishek2',
      'Dummy_xpcover@test2222.com',
      3293232222030,
      'Sinha Abhishek2',
      'Dummy_xpcover@test2222.com',
      '3293232222030',
      '1999-01-08',
      '1999-01-06',
      false,
      'BYEIE149000',
      'UNI SERHEIE ALLAHABAD VICES PVT. LTD',
      '{"23523837445", "2325048"}',
      'Palaspa JALIBEIN Panvel Raigarh',
      'SECONDFAX820202WERYU');
