CREATE TABLE state(
   id               BIGSERIAL NOT NULL,
   country_id       INT,
   country_code     VARCHAR(10) NOT NULL,
   subdivision_code VARCHAR(10) NOT NULL,
   subdivision_name VARCHAR(100),
   level            VARCHAR(50),
   tax_rate         DECIMAL
);
INSERT INTO state (
country_id,
country_code,
subdivision_code,
subdivision_name,
level,
tax_rate ) VALUES
(3,'AF','BAL','Balkh','Province',0),
(3,'AF','BAM','Bāmyān','Province',0),
(3,'AF','BDG','Bādghīs','Province',0),
(3,'AF','BDS','Badakhshān','Province',0),
(3,'AF','BGL','Baghlān','Province',0),
(3,'AF','DAY','Dāykundī','Province',0),
(3,'AF','FRA','Farāh','Province',0),
(3,'AF','FYB','Fāryāb','Province',0),
(3,'AF','GHA','Ghaznī','Province',0),
(3,'AF','GHO','Ghōr','Province',0),
(3,'AF','HEL','Helmand','Province',0),
(3,'AF','HER','Herāt','Province',0),
(3,'AF','JOW','Jowzjān','Province',0),
(3,'AF','KAB','Kābul','Province',0),
(3,'AF','KAN','Kandahār','Province',0),
(3,'AF','KAP','Kāpīsā','Province',0),
(3,'AF','KDZ','Kunduz','Province',0),
(3,'AF','KHO','Khōst','Province',0),
(3,'AF','KNR','Kunar','Province',0),
(3,'AF','LAG','Laghmān','Province',0),
(3,'AF','LOG','Lōgar','Province',0),
(3,'AF','NAN','Nangarhār','Province',0),
(3,'AF','NIM','Nīmrōz','Province',0),
(3,'AF','NUR','Nūristān','Province',0),
(3,'AF','PAN','Panjshayr','Province',0),
(3,'AF','PAR','Parwān','Province',0),
(3,'AF','PIA','Paktīā','Province',0),
(3,'AF','PKA','Paktīkā','Province',0),
(3,'AF','SAM','Samangān','Province',0),
(3,'AF','SAR','Sar-e Pul','Province',0),
(3,'AF','TAK','Takhār','Province',0),
(3,'AF','URU','Uruzgān','Province',0),
(3,'AF','WAR','Wardak','Province',0),
(3,'AF','ZAB','Zābul','Province',0),
(10,'AR','A','Salta','Province',20),
(10,'AR','B','Buenos Aires','Province',20),
(10,'AR','C','Ciudad Autónoma de Buenos Aires','City',20),
(10,'AR','D','San Luis','Province',20),
(10,'AR','E','Entre Ríos','Province',20),
(10,'AR','F','La Rioja','Province',20),
(10,'AR','G','Santiago del Estero','Province',20),
(10,'AR','H','Chaco','Province',20),
(10,'AR','J','San Juan','Province',20),
(10,'AR','K','Catamarca','Province',20),
(10,'AR','L','La Pampa','Province',20),
(10,'AR','M','Mendoza','Province',20),
(10,'AR','N','Misiones','Province',20),
(10,'AR','P','Formosa','Province',20),
(10,'AR','Q','Neuquén','Province',20),
(10,'AR','R','Río Negro','Province',20),
(10,'AR','S','Santa Fe','Province',20),
(10,'AR','T','Tucumán','Province',20),
(10,'AR','U','Chubut','Province',20),
(10,'AR','V','Tierra del Fuego','Province',20),
(10,'AR','W','Corrientes','Province',20),
(10,'AR','X','Córdoba','Province',20),
(10,'AR','Y','Jujuy','Province',20),
(10,'AR','Z','Santa Cruz','Province',20),
(13,'AU','ACT','Australian Capital Territory','Territory',20),
(13,'AU','NSW','New South Wales','State',20),
(13,'AU','NT','Northern Territory','Territory',20),
(13,'AU','QLD','Queensland','State',20),
(13,'AU','SA','South Australia','State',20),
(13,'AU','TAS','Tasmania','State',20),
(13,'AU','VIC','Victoria','State',20),
(13,'AU','WA','Western Australia','State',20),
(20,'BE','BRU','Bruxelles-Capitale, Région de (fr)','Region',null),
(20,'BE','BRU','Brussels Hoofdstedelijk Gewest (nl)','Region',null),
(20,'BE','VAN','Antwerpen (VLG)','Province',null),
(20,'BE','VBR','Vlaams Brabant (VLG)','Province',null),
(20,'BE','VLG','Vlaamse Gewest (nl)','Region',null),
(20,'BE','VLI','Limburg (VLG)','Province',null),
(20,'BE','VOV','Oost-Vlaanderen (VLG)','Province',null),
(20,'BE','VWV','West-Vlaanderen (VLG)','Province',null),
(20,'BE','WAL','Wallonne, Région (fr)','Region',null),
(20,'BE','WBR','Brabant Wallon (WAL)','Province',null),
(20,'BE','WHT','Hainaut (WAL)','Province',null),
(20,'BE','WLG','Liège (WAL)','Province',null),
(20,'BE','WLX','Luxembourg (WAL)','Province',null),
(20,'BE','WNA','Namur (WAL)','Province',null),
(35,'BY','HM','Horad Minsk (be) - BrestGorod Minsk (ru)','City',21),
(35,'BY','BR','Brestskaya voblasts'' (be) - Brestskaya oblast'' (ru)','Oblast',21),
(35,'BY','HO','Homyel''skaya voblasts'' (be) - Gomel''skaya oblast'' (ru)','Oblast',21),
(35,'BY','HR','Hrodzenskaya voblasts'' (be) - Grodnenskaya oblast'' (ru)','Oblast',21),
(35,'BY','MA','Mahilyowskaya voblasts'' (be) - Mogilevskaya oblast'' (ru)','Oblast',21),
(35,'BY','MI','Minskaya voblasts'' (be) - Minskaya oblast'' (ru)','Oblast',21),
(35,'BY','VI','Vitsyebskaya voblasts'' (be) - Vitebskaya oblast'' (ru)','Oblast',21),
('31','BR','AC','Acre','State',18),
('31','BR','AL','Alagoas','State',18),
('31','BR','AM','Amazonas','State',18),
('31','BR','AP','Amapá','State',18),
('31','BR','BA','Bahia','State',18),
('31','BR','CE','Ceará','State',18),
('31','BR','DF','Distrito Federal','Federal district',18),
('31','BR','ES','Espírito Santo','State',18),
('31','BR','GO','Goiás','State',18),
('31','BR','MA','Maranhão','State',18),
('31','BR','MG','Minas Gerais','State',18),
('31','BR','MS','Mato Grosso do Sul','State',18),
('31','BR','MT','Mato Grosso','State',18),
('31','BR','PA','Pará','State',18),
('31','BR','PB','Paraíba','State',18),
('31','BR','PE','Pernambuco','State',18),
('31','BR','PI','Piauí','State',18),
('31','BR','PR','Paraná','State',18),
('31','BR','RJ','Rio de Janeiro','State',18),
('31','BR','RN','Rio Grande do Norte','State',18),
('31','BR','RO','Rondônia','State',18),
('31','BR','RR','Roraima','State',18),
('31','BR','RS','Rio Grande do Sul','State',18),
('31','BR','SC','Santa Catarina','State',18),
('31','BR','SE','Sergipe','State',18),
('31','BR','SP','São Paulo','State',18),
('31','BR','TO','Tocantins','State',18),
('37','CA','AB','Alberta','Province',5),
('37','CA','BC','British Columbia','Province',5),
('37','CA','MB','Manitoba','Province',5),
('37','CA','NB','New Brunswick','Province',5),
('37','CA','NL','Newfoundland and Labrador','Province',5),
('37','CA','NS','Nova Scotia','Province',5),
('37','CA','NT','Northwest Territories','Territory',5),
('37','CA','NU','Nunavut','Territory',5),
('37','CA','ON','Ontario','Province',5),
('37','CA','PE','Prince Edward Island','Province',5),
('37','CA','QC','Quebec','Province',5),
('37','CA','SK','Saskatchewan','Province',5),
('37','CA','YT','Yukon Territory','Territory',5),
('45','CL','AI','Aisén del General Carlos Ibáñez del Campo','Region',19),
('45','CL','AN','Antofagasta','Region',19),
('45','CL','AP','Arica y Parinacota','Region',19),
('45','CL','AR','Araucanía','Region',19),
('45','CL','AT','Atacama','Region',19),
('45','CL','BI','Bío-Bío','Region',19),
('45','CL','CO','Coquimbo','Region',19),
('45','CL','LI','Libertador General Bernardo O''Higgins','Region',19),
('45','CL','LL','Los Lagos','Region',19),
('45','CL','LR','Los Ríos','Region',19),
('45','CL','MA','Magallanes','Region',19),
('45','CL','ML','Maule','Region',19),
('45','CL','RM','Región Metropolitana de Santiago','Region',19),
('45','CL','TA','Tarapacá','Region',19),
('45','CL','VS','Valparaíso','Region',19),
('48','CO','AMA','Amazonas','Department',19),
('48','CO','ANT','Antioquia','Department',19),
('48','CO','ARA','Arauca','Department',19),
('48','CO','ATL','Atlántico','Department',19),
('48','CO','BOL','Bolívar','Department',19),
('48','CO','BOY','Boyacá','Department',19),
('48','CO','CAL','Caldas','Department',19),
('48','CO','CAQ','Caquetá','Department',19),
('48','CO','CAS','Casanare','Department',19),
('48','CO','CAU','Cauca','Department',19),
('48','CO','CES','Cesar','Department',19),
('48','CO','CHO','Chocó','Department',19),
('48','CO','COR','Córdoba','Department',19),
('48','CO','CUN','Cundinamarca','Department',19),
('48','CO','DC','Distrito Capital de Bogotá','Capital district',19),
('48','CO','GUA','Guainía','Department',19),
('48','CO','GUV','Guaviare','Department',19),
('48','CO','HUI','Huila','Department',19),
('48','CO','LAG','La Guajira','Department',19),
('48','CO','MAG','Magdalena','Department',19),
('48','CO','MET','Meta','Department',19),
('48','CO','NAR','Nariño','Department',19),
('48','CO','NSA','Norte de Santander','Department',19),
('48','CO','PUT','Putumayo','Department',19),
('48','CO','QUI','Quindío','Department',19),
('48','CO','RIS','Risaralda','Department',19),
('48','CO','SAN','Santander','Department',19),
('48','CO','SAP','San Andrés, Providencia y Santa Catalina','Department',19),
('48','CO','SUC','Sucre','Department',19),
('48','CO','TOL','Tolima','Department',19),
('48','CO','VAC','Valle del Cauca','Department',19),
('48','CO','VAU','Vaupés','Department',19),
('48','CO','VID','Vichada','Department',19),
('39','CD','BC','Bas-Congo','Province',null),
('39','CD','BN','Bandundu','Province',null),
('39','CD','EQ','Équateur','Province',null),
('39','CD','KA','Katanga','Province',null),
('39','CD','KE','Kasai-Oriental','Province',null),
('39','CD','KN','Kinshasa','City',null),
('39','CD','KW','Kasai-Occidental','Province',null),
('39','CD','MA','Maniema','Province',null),
('39','CD','NK','Nord-Kivu','Province',null),
('39','CD','OR','Orientale','Province',null),
('39','CD','SK','Sud-Kivu','Province',null),
('55','CZ','JC','Jihoceský kraj','Region',null),
('55','CZ','JM','Jihomoravský kraj','Region',null),
('55','CZ','KA','Karlovarský kraj','Region',null),
('55','CZ','KR','Královéhradecký kraj','Region',null),
('55','CZ','LI','Liberecký kraj','Region',null),
('55','CZ','MO','Moravskoslezský kraj','Region',null),
('55','CZ','OL','Olomoucký kraj','Region',null),
('55','CZ','PA','Pardubický kraj','Region',null),
('55','CZ','PL','Plzeňský kraj','Region',null),
('55','CZ','PR','Praha, hlavní mešto','Region',null),
('55','CZ','ST','Středočeský kraj','Region',null),
('55','CZ','US','Ústecký kraj','Region',null),
('55','CZ','VY','Vysočina','Region',null),
('55','CZ','ZL','Zlínský kraj','Region',null),
('62','EC','A','Azuay','Province',12),
('62','EC','B','Bolívar','Province',12),
('62','EC','C','Carchi','Province',12),
('62','EC','D','Orellana','Province',12),
('62','EC','E','Esmeraldas','Province',12),
('62','EC','F','Cañar','Province',12),
('62','EC','G','Guayas','Province',12),
('62','EC','H','Chimborazo','Province',12),
('62','EC','I','Imbabura','Province',12),
('62','EC','L','Loja','Province',12),
('62','EC','M','Manabí','Province',12),
('62','EC','N','Napo','Province',12),
('62','EC','O','El Oro','Province',12),
('62','EC','P','Pichincha','Province',12),
('62','EC','R','Los Ríos','Province',12),
('62','EC','S','Morona-Santiago','Province',12),
('62','EC','SD','Santo Domingo de los Tsáchilas','Province',12),
('62','EC','SE','Santa Elena','Province',12),
('62','EC','T','Tungurahua','Province',12),
('62','EC','U','Sucumbíos','Province',12),
('62','EC','W','Galápagos','Province',12),
('62','EC','X','Cotopaxi','Province',12),
('62','EC','Y','Pastaza','Province',12),
('62','EC','Z','Zamora-Chinchipe','Province',12),
('64','EG','ALX','Al Iskandarīyah','Governorate',14),
('64','EG','ASN','Aswān','Governorate',14),
('64','EG','AST','Asyūţ','Governorate',14),
('64','EG','BA','Al Baḩr al Aḩmar','Governorate',14),
('64','EG','BH','Al Buḩayrah','Governorate',14),
('64','EG','BNS','Banī Suwayf','Governorate',14),
('64','EG','C','Al Qāhirah','Governorate',14),
('64','EG','DK','Ad Daqahlīyah','Governorate',14),
('64','EG','DT','Dumyāţ','Governorate',14),
('64','EG','FYM','Al Fayyūm','Governorate',14),
('64','EG','GH','Al Gharbīyah','Governorate',14),
('64','EG','GZ','Al Jīzah','Governorate',14),
('64','EG','HU','Ḩulwān','Governorate',14),
('64','EG','IS','Al Ismā''īlīyah','Governorate',14),
('64','EG','JS','Janūb Sīnā''','Governorate',14),
('64','EG','KB','Al Qalyūbīyah','Governorate',14),
('64','EG','KFS','Kafr ash Shaykh','Governorate',14),
('64','EG','KN','Qinā','Governorate',14),
('64','EG','LX','Al Uqşur','Governorate',14),
('64','EG','MN','Al Minyā','Governorate',14),
('64','EG','MNF','Al Minūfīyah','Governorate',14),
('64','EG','MT','Maţrūḩ','Governorate',14),
('64','EG','PTS','Būr Sa‘īd','Governorate',14),
('64','EG','SHG','Sūhāj','Governorate',14),
('64','EG','SHR','Ash Sharqīyah','Governorate',14),
('64','EG','SIN','Shamāl Sīnā''','Governorate',14),
('64','EG','SU','As Sādis min Uktūbar','Governorate',14),
('64','EG','SUZ','As Suways','Governorate',14),
('64','EG','WAD','Al Wādī al Jadīd','Governorate',14),
('68','ET','AA','Adis Abeba','Administration',19.87),
('68','ET','AF','Afar','State',19.87),
('68','ET','AM','Amara','State',19.87),
('68','ET','BE','Binshangul Gumuz','State',19.87),
('68','ET','DD','Dire Dawa','Administration',19.87),
('68','ET','GA','Gambela Hizboch','State',19.87),
('68','ET','HA','Hareri Hizb','State',19.87),
('68','ET','OR','Oromiya','State',19.87),
('68','ET','SN','YeDebub Biheroch Bihereseboch na Hizboch','State',19.87),
('68','ET','SO','Sumale','State',19.87),
('68','ET','TI','Tigray','State',19.87),
('70','FJ','C','Central','Division',9),
('70','FJ','E','Eastern','Division',9),
('70','FJ','N','Northern','Division',9),
('70','FJ','R','Rotuma','Dependency',9),
('70','FJ','W','Western','Division',9),
('56','DE','BB','Brandenburg','Land',19),
('56','DE','BE','Berlin','Land',19),
('56','DE','BW','Baden-Württemberg','Land',19),
('56','DE','BY','Bayern','Land',19),
('56','DE','HB','Bremen','Land',19),
('56','DE','HE','Hessen','Land',19),
('56','DE','HH','Hamburg','Land',19),
('56','DE','MV','Mecklenburg-Vorpommern','Land',19),
('56','DE','NI','Niedersachsen','Land',19),
('56','DE','NW','Nordrhein-Westfalen','Land',19),
('56','DE','RP','Rheinland-Pfalz','Land',19),
('56','DE','SH','Schleswig-Holstein','Land',19),
('56','DE','SL','Saarland','Land',19),
('56','DE','SN','Sachsen','Land',19),
('56','DE','ST','Sachsen-Anhalt','Land',19),
('56','DE','TH','Thüringen','Land',19),
('81','GH','AA','Greater Accra','Region',18.13),
('81','GH','AH','Ashanti','Region',18.13),
('81','GH','BA','Brong-Ahafo','Region',18.13),
('81','GH','CP','Central','Region',18.13),
('81','GH','EP','Eastern','Region',18.13),
('81','GH','NP','Northern','Region',18.13),
('81','GH','TV','Volta','Region',18.13),
('81','GH','UE','Upper East','Region',18.13),
('81','GH','UW','Upper West','Region',18.13),
('81','GH','WP','Western','Region',18.13),
('98','HT','AR','Artibonite','Department',null),
('98','HT','CE','Centre','Department',null),
('98','HT','GA','Grande-Anse','Department',null),
('98','HT','ND','Nord','Department',null),
('98','HT','NE','Nord-Est','Department',null),
('98','HT','NI','Nippes','Department',null),
('98','HT','NO','Nord-Ouest','Department',null),
('98','HT','OU','Ouest','Department',null),
('98','HT','SD','Sud','Department',null),
('98','HT','SE','Sud-Est','Department',null),
('99','HU','BA','Baranya','County',27),
('99','HU','BC','Békéscsaba','City of county right',27),
('99','HU','BE','Békés','County',27),
('99','HU','BK','Bács-Kiskun','County',27),
('99','HU','BU','Budapest','Capital City',27),
('99','HU','BZ','Borsod-Abaúj-Zemplén','County',27),
('99','HU','CS','Csongrád','County',27),
('99','HU','DE','Debrecen','City of county right',27),
('99','HU','DU','Dunaujváros','City of county right',27),
('99','HU','EG','Eger','City of county right',27),
('99','HU','FE','Fejér','County',27),
('99','HU','GS','Gyór-Moson-Sopron','County',27),
('99','HU','GY','Gyór','City of county right',27),
('99','HU','HB','Hajdú-Bihar','County',27),
('99','HU','HE','Heves','County',27),
('99','HU','HV','Hódmezóvásárhely','City of county right',27),
('99','HU','JN','Jász-Nagykun-Szolnok','County',27),
('99','HU','KE','Komárom-Esztergom','County',27),
('99','HU','KM','Kecskemét','City of county right',27),
('99','HU','KV','Kaposvár','City of county right',27),
('99','HU','MI','Miskolc','City of county right',27),
('99','HU','NK','Nagykanizsa','City of county right',27),
('99','HU','NO','Nógrád','County',27),
('99','HU','NY','Nyíregyháza','City of county right',27),
('99','HU','PE','Pest','County',27),
('99','HU','PS','Pécs','City of county right',27),
('99','HU','SD','Szeged','City of county right',27),
('99','HU','SF','Székesfehérvár','City of county right',27),
('99','HU','SH','Szombathely','City of county right',27),
('99','HU','SK','Szolnok','City of county right',27),
('99','HU','SN','Sopron','City of county right',27),
('99','HU','SO','Somogy','County',27),
('99','HU','SS','Szekszárd','City of county right',27),
('99','HU','ST','Salgótarján','City of county right',27),
('99','HU','SZ','Szabolcs-Szatmár-Bereg','County',27),
('99','HU','TB','Tatabánya','City of county right',27),
('99','HU','TO','Tolna','County',27),
('99','HU','VA','Vas','County',27),
('99','HU','VE','Veszprém','County',27),
('99','HU','VM','Veszprém','City of county right',27),
('99','HU','ZA','Zala','County',27),
('99','HU','ZE','Zalaegerszeg','City of county right',27),
('104','IN','AN','Andaman and Nicobar Islands','Union territory',18),
('104','IN','AP','Andhra Pradesh','State',18),
('104','IN','AR','Arunachal Pradesh','State',18),
('104','IN','AS','Assam','State',18),
('104','IN','BR','Bihar','State',18),
('104','IN','CH','Chandigarh','Union territory',18),
('104','IN','CT','Chhattisgarh','State',18),
('104','IN','DD','Daman and Diu','Union territory',18),
('104','IN','DL','Delhi','Union territory',18),
('104','IN','DN','Dadra and Nagar Haveli','Union territory',18),
('104','IN','GA','Goa','State',18),
('104','IN','GJ','Gujarat','State',18),
('104','IN','HP','Himachal Pradesh','State',18),
('104','IN','HR','Haryana','State',18),
('104','IN','JH','Jharkhand','State',18),
('104','IN','JK','Jammu and Kashmir','State',18),
('104','IN','KA','Karnataka','State',18),
('104','IN','KL','Kerala','State',18),
('104','IN','LD','Lakshadweep','Union territory',18),
('104','IN','MH','Maharashtra','State',18),
('104','IN','ML','Meghalaya','State',18),
('104','IN','MN','Manipur','State',18),
('104','IN','MP','Madhya Pradesh','State',18),
('104','IN','MZ','Mizoram','State',18),
('104','IN','NL','Nagaland','State',18),
('104','IN','OR','Orissa','State',18),
('104','IN','PB','Punjab','State',18),
('104','IN','PY','Pondicherry','Union territory',18),
('104','IN','RJ','Rajasthan','State',18),
('104','IN','SK','Sikkim','State',18),
('104','IN','TN','Tamil Nadu','State',18),
('104','IN','TR','Tripura','State',18),
('104','IN','UP','Uttar Pradesh','State',18),
('104','IN','WB','West Bengal','State',18),
('100','ID','AC','Aceh','Autononous province',10),
('100','ID','BA','Bali','Province',10),
('100','ID','BB','Bangka Belitung','Province',10),
('100','ID','BE','Bengkulu','Province',10),
('100','ID','BT','Banten','Province',10),
('100','ID','GO','Gorontalo','Province',10),
('100','ID','JA','Jambi','Province',10),
('100','ID','JB','Jawa Barat','Province',10),
('100','ID','JI','Jawa Timur','Province',10),
('100','ID','JK','Jakarta Raya','Special district',10),
('100','ID','JT','Jawa Tengah','Province',10),
('100','ID','KB','Kalimantan Barat','Province',10),
('100','ID','KI','Kalimantan Timur','Province',10),
('100','ID','KR','Kepulauan Riau','Province',10),
('100','ID','KS','Kalimantan Selatan','Province',10),
('100','ID','KT','Kalimantan Tengah','Province',10),
('100','ID','LA','Lampung','Province',10),
('100','ID','MA','Maluku','Province',10),
('100','ID','MU','Maluku Utara','Province',10),
('100','ID','NB','Nusa Tenggara Barat','Province',10),
('100','ID','NT','Nusa Tenggara Timur','Province',10),
('100','ID','PA','Papua','Province',10),
('100','ID','PB','Papua Barat','Province',10),
('100','ID','PB','Papua Barat','Province',10),
('100','ID','RI','Riau','Province',10),
('100','ID','SA','Sulawesi Utara','Province',10),
('100','ID','SB','Sumatera Barat','Province',10),
('100','ID','SG','Sulawesi Tenggara','Province',10),
('100','ID','SN','Sulawesi Selatan','Province',10),
('100','ID','SS','Sumatera Selatan','Province',10),
('100','ID','ST','Sulawesi Tengah','Province',10),
('100','ID','SU','Sumatera Utara','Province',10),
('100','ID','YO','Yogyakarta','Special region',10),
('106','IQ','AN','Al Anbār','Governorate',0),
('106','IQ','AR','Arbīl','Governorate',0),
('106','IQ','BA','Al Başrah','Governorate',0),
('106','IQ','BB','Bābil','Governorate',0),
('106','IQ','BG','Baghdād','Governorate',0),
('106','IQ','DA','Dahūk','Governorate',0),
('106','IQ','DI','Diyālá','Governorate',0),
('106','IQ','DQ','Dhī Qār','Governorate',0),
('106','IQ','KA','Karbalā''','Governorate',0),
('106','IQ','MA','Maysān','Governorate',0),
('106','IQ','MU','Al Muthannáá','Governorate',0),
('106','IQ','NA','An Najaf','Governorate',0),
('106','IQ','NI','Nīnawá','Governorate',0),
('106','IQ','QA','Al Qādisīyah','Governorate',0),
('106','IQ','SD','Şalāḩ ad Dīn','Governorate',0),
('106','IQ','SU','As Sulaymānīyah','Governorate',0),
('106','IQ','TS','At Ta''mīm','Governorate',0),
('106','IQ','WA','Wāsiţ','Governorate',0),
('101','IE','CE','Clare','County',23),
('101','IE','CN','Cavan','County',23),
('101','IE','CO','Cork','County',23),
('101','IE','CW','Carlow','County',23),
('101','IE','D','Dublin','County',23),
('101','IE','DL','Donegal','County',23),
('101','IE','G','Galway','County',23),
('101','IE','KE','Kildare','County',23),
('101','IE','KK','Kilkenny','County',23),
('101','IE','KY','Kerry','County',23),
('101','IE','LD','Longford','County',23),
('101','IE','LH','Louth','County',23),
('101','IE','LK','Limerick','County',23),
('101','IE','LM','Leitrim','County',23),
('101','IE','LS','Laois','County',23),
('101','IE','MH','Meath','County',23),
('101','IE','MN','Monaghan','County',23),
('101','IE','MO','Mayo','County',23),
('101','IE','OY','Offaly','County',23),
('101','IE','RN','Roscommon','County',23),
('101','IE','SO','Sligo','County',23),
('101','IE','TA','Tipperary','County',23),
('101','IE','WD','Waterford','County',23),
('101','IE','WH','Westmeath','County',23),
('101','IE','WW','Wicklow','County',23),
('101','IE','WX','Wexford','County',23),
('102','IL','D','HaDarom','District',17),
('102','IL','HA','H̱efa','District',17),
('102','IL','JM','Yerushalayim','District',17),
('102','IL','M','HaMerkaz','District',17),
('102','IL','TA','Tel-Aviv','District',17),
('102','IL','Z','Ha Ẕafon','District',17),
('109','IT','AG','Agrigento','Province',22),
('109','IT','AL','Alessandria','Province',22),
('109','IT','AN','Ancona','Province',22),
('109','IT','AO','Aoste (fr)','Province',22),
('109','IT','AP','Ascoli Piceno','Province',22),
('109','IT','AQ','L''Aquila','Province',22),
('109','IT','AR','Arezzo','Province',22),
('109','IT','AT','Asti','Province',22),
('109','IT','AV','Avellino','Province',22),
('109','IT','BA','Bari','Province',22),
('109','IT','BG','Bergamo','Province',22),
('109','IT','BI','Biella','Province',22),
('109','IT','BL','Belluno','Province',22),
('109','IT','BN','Benevento','Province',22),
('109','IT','BO','Bologna','Province',22),
('109','IT','BR','Brindisi','Province',22),
('109','IT','BS','Brescia','Province',22),
('109','IT','BT','Barletta-Andria-Trani','Province',22),
('109','IT','BZ','Bozen (de)','Province',22),
('109','IT','CA','Cagliari','Province',22),
('109','IT','CB','Campobasso','Province',22),
('109','IT','CE','Caserta','Province',22),
('109','IT','CH','Chieti','Province',22),
('109','IT','CI','Carbonia-Iglesias','Province',22),
('109','IT','CL','Caltanissetta','Province',22),
('109','IT','CN','Cuneo','Province',22),
('109','IT','CO','Como','Province',22),
('109','IT','CR','Cremona','Province',22),
('109','IT','CS','Cosenza','Province',22),
('109','IT','CT','Catania','Province',22),
('109','IT','CZ','Catanzaro','Province',22),
('109','IT','EN','Enna','Province',22),
('109','IT','FC','Forlì-Cesena','Province',22),
('109','IT','FE','Ferrara','Province',22),
('109','IT','FG','Foggia','Province',22),
('109','IT','FI','Firenze','Province',22),
('109','IT','FM','Fermo','Province',22),
('109','IT','FR','Frosinone','Province',22),
('109','IT','GE','Genova','Province',22),
('109','IT','GO','Gorizia','Province',22),
('109','IT','GR','Grosseto','Province',22),
('109','IT','IM','Imperia','Province',22),
('109','IT','IS','Isernia','Province',22),
('109','IT','KR','Crotone','Province',22),
('109','IT','LC','Lecco','Province',22),
('109','IT','LE','Lecce','Province',22),
('109','IT','LI','Livorno','Province',22),
('109','IT','LO','Lodi','Province',22),
('109','IT','LT','Latina','Province',22),
('109','IT','LU','Lucca','Province',22),
('109','IT','MB','Monza e Brianza','Province',22),
('109','IT','MC','Macerata','Province',22),
('109','IT','ME','Messina','Province',22),
('109','IT','MI','Milano','Province',22),
('109','IT','MN','Mantova','Province',22),
('109','IT','MO','Modena','Province',22),
('109','IT','MS','Massa-Carrara','Province',22),
('109','IT','MT','Matera','Province',22),
('109','IT','NA','Napoli','Province',22),
('109','IT','NO','Novara','Province',22),
('109','IT','NU','Nuoro','Province',22),
('109','IT','OG','Ogliastra','Province',22),
('109','IT','OR','Oristano','Province',22),
('109','IT','OT','Olbia-Tempio','Province',22),
('109','IT','PA','Palermo','Province',22),
('109','IT','PC','Piacenza','Province',22),
('109','IT','PD','Padova','Province',22),
('109','IT','PE','Pescara','Province',22),
('109','IT','PG','Perugia','Province',22),
('109','IT','PI','Pisa','Province',22),
('109','IT','PN','Pordenone','Province',22),
('109','IT','PO','Prato','Province',22),
('109','IT','PR','Parma','Province',22),
('109','IT','PT','Pistoia','Province',22),
('109','IT','PU','Pesaro e Urbino','Province',22),
('109','IT','PV','Pavia','Province',22),
('109','IT','PZ','Potenza','Province',22),
('109','IT','RA','Ravenna','Province',22),
('109','IT','RC','Reggio Calabria','Province',22),
('109','IT','RE','Reggio Emilia','Province',22),
('109','IT','RG','Ragusa','Province',22),
('109','IT','RI','Rieti','Province',22),
('109','IT','RM','Roma','Province',22),
('109','IT','RN','Rimini','Province',22),
('109','IT','RO','Rovigo','Province',22),
('109','IT','SA','Salerno','Province',22),
('109','IT','SI','Siena','Province',22),
('109','IT','SO','Sondrio','Province',22),
('109','IT','SP','La Spezia','Province',22),
('109','IT','SR','Siracusa','Province',22),
('109','IT','SS','Sassari','Province',22),
('109','IT','SV','Savona','Province',22),
('109','IT','TA','Taranto','Province',22),
('109','IT','TE','Teramo','Province',22),
('109','IT','TN','Trento','Province',22),
('109','IT','TO','Torino','Province',22),
('109','IT','TP','Trapani','Province',22),
('109','IT','TR','Terni','Province',22),
('109','IT','TS','Trieste','Province',22),
('109','IT','TV','Treviso','Province',22),
('109','IT','UD','Udine','Province',22),
('109','IT','VA','Varese','Province',22),
('109','IT','VB','Verbano-Cusio-Ossola','Province',22),
('109','IT','VC','Vercelli','Province',22),
('109','IT','VE','Venezia','Province',22),
('109','IT','VI','Vicenza','Province',22),
('109','IT','VR','Verona','Province',22),
('109','IT','VS','Medio Campidano','Province',22),
('109','IT','VT','Viterbo','Province',22),
('109','IT','VV','Vibo Valentia','Province',22),
('112','JO','AJ','ʽAjlūn','Governorate',16),
('112','JO','AM','‘Ammān (Al ‘A̅şimah)','Governorate',16),
('112','JO','AQ','Al''Aqaba','Governorate',16),
('112','JO','AT','Aţ Ţafīlah','Governorate',16),
('112','JO','AZ','Az Zarqā''','Governorate',16),
('112','JO','BA','Al Balqā''','Governorate',16),
('112','JO','IR','Irbid','Governorate',16),
('112','JO','JA','Jarash','Governorate',16),
('112','JO','KA','AI Karak','Governorate',16),
('112','JO','MA','AI Mafraq','Governorate',16),
('112','JO','MD','Mādabā','Governorate',16),
('112','JO','MN','Ma''ān','Governorate',16),
('124','KZ','AKM','Aqmola oblysy','Region',12),
('124','KZ','AKT','Aqtöbe oblysy','Region',12),
('124','KZ','ALA','Almaty','City',12),
('124','KZ','ALM','Almaty oblysy','Region',12),
('124','KZ','AST','Astana','City',12),
('124','KZ','ATY','Atyraū oblysy','Region',12),
('124','KZ','KAR','Qaraghandy oblysy','Region',12),
('124','KZ','KUS','Qostanay oblysy','Region',12),
('124','KZ','KZY','Qyzylorda oblysy','Region',12),
('124','KZ','MAN','Mangghystaū oblysy','Region',12),
('124','KZ','PAV','Pavlodar oblysy','Region',12),
('124','KZ','SEV','Soltüstik Qazaqstan oblysy','Region',12),
('124','KZ','VOS','Shyghys Qazaqstan oblysy','Region',12),
('124','KZ','YUZ','Ongtüstik Qazaqstan oblysy','Region',12),
('124','KZ','ZAP','Batys Qazaqstan oblysy','Region',12),
('124','KZ','ZHA','Zhambyl oblysy','Region',12),
('122','KW','AH','Al Aḩmadī','Governorate',0),
('122','KW','FA','Al Farwānīyah','Governorate',0),
('122','KW','HA','Ḩawallī','Governorate',0),
('122','KW','JA','Al Jahrā’','Governorate',0),
('122','KW','KU','Al Kuwayt (Al ‘Āşimah)','Governorate',0),
('122','KW','MU','Mubārak al Kabīr','Governorate',0),
('115','KG','B','Batken','Region',null),
('115','KG','C','Chü','Region',null),
('115','KG','GB','Bishkek','City',null),
('115','KG','J','Jalal-Abad','Region',null),
('115','KG','N','Naryn','Region',null),
('115','KG','O','Osh','Region',null),
('115','KG','T','Talas','Region',null),
('115','KG','Y','Ysyk-Köl','Region',null),
('141','MG','A','Toamasina','Province',null),
('141','MG','D','Antsiranana','Province',null),
('141','MG','F','Fianarantsoa','Province',null),
('141','MG','M','Mahajanga','Province',null),
('141','MG','T','Antananarivo','Province',null),
('141','MG','U','Toliara','Province',null),
('153','MU','AG','Agalega Islands','Dependency',15),
('153','MU','BL','Black River','District',15),
('153','MU','BR','Beau Bassin-Rose Hill','City',15),
('153','MU','CC','Cargados Carajos Shoals','Dependency',15),
('153','MU','CU','Curepipe','City',15),
('153','MU','FL','Flacq','District',15),
('153','MU','GP','Grand Port','District',15),
('153','MU','MO','Moka','District',15),
('153','MU','PA','Pamplemousses','District',15),
('153','MU','PL','Part Louis','District',15),
('153','MU','PU','Port Louis','City',15),
('153','MU','PW','Plaines wilhems','District',15),
('153','MU','QB','Quatre Bornes','City',15),
('153','MU','RO','Rodrigues Island','Dependency',15),
('153','MU','RR','Rivière du Rempart','District',15),
('153','MU','SA','Savanne','District',15),
('153','MU','VP','Vacoas-Phoenix','City',15),
('156','MX','AGU','Aguascalientes','State',null),
('156','MX','BCN','Baja California','State',null),
('156','MX','BCS','Baja California Sur','State',null),
('156','MX','CAM','Campeche','State',null),
('156','MX','CHH','Chihuahua','State',null),
('156','MX','CHP','Chiapas','State',null),
('156','MX','COA','Coahuila','State',null),
('156','MX','COL','Colima','State',null),
('156','MX','DIF','Distrito Federal','Federal District',null),
('156','MX','DUR','Durango','State',null),
('156','MX','GRO','Guerrero','State',null),
('156','MX','GUA','Guanajuato','State',null),
('156','MX','HID','Hidalgo','State',null),
('156','MX','JAL','Jalisco','State',null),
('156','MX','MEX','México','State',null),
('156','MX','MIC','Michoacán','State',null),
('156','MX','MOR','Morelos','State',null),
('156','MX','NAY','Nayarit','State',null),
('156','MX','NLE','Nuevo León','State',null),
('156','MX','OAX','Oaxaca','State',null),
('156','MX','PUE','Puebla','State',null),
('156','MX','QUE','Querétaro','State',null),
('156','MX','ROO','Quintana Roo','State',null),
('156','MX','SIN','Sinaloa','State',null),
('156','MX','SLP','San Luis Potosí','State',null),
('156','MX','SON','Sonora','State',null),
('156','MX','TAB','Tabasco','State',null),
('156','MX','TAM','Tamaulipas','State',null),
('156','MX','TLA','Tlaxcala','State',null),
('156','MX','VER','Veracruz','State',null),
('156','MX','YUC','Yucatán','State',null),
('156','MX','ZAC','Zacatecas','State',null),
('137','MC','CL','La Colle','Quartier',null),
('137','MC','CO','La Condamine','Quartier',null),
('137','MC','FO','Fontvieille','Quartier',null),
('137','MC','FO','Fontvieille','Quartier',null),
('137','MC','GA','La Gare','Quartier',null),
('137','MC','JE','Jardin Exotique','Quartier',null),
('137','MC','LA','Larvotto','Quartier',null),
('137','MC','MA','Malbousquet','Quartier',null),
('137','MC','MC','Monte-Carlo','Quartier',null),
('137','MC','MG','Moneghetti','Quartier',null),
('137','MC','MO','Monaco-Ville','Quartier',null),
('137','MC','MU','Moulins','Quartier',null),
('137','MC','PH','Port-Hercule','Quartier',null),
('137','MC','SD','Sainte-Dévote','Quartier',null),
('137','MC','SO','La Source','Quartier',null),
('137','MC','SP','Spélugues','Quartier',null),
('137','MC','SR','Saint-Roman','Quartier',null),
('137','MC','VR','Vallon de la Rousse','Quartier',null),
('167','NP','1','Madhyamanchal','Development region',null),
('167','NP','2','Madhya Pashchimanchal','Development region',null),
('167','NP',3,'Pashchimanchal','Development region',null),
('167','NP','4','Purwanchal','Development region',null),
('167','NP','5','Sudur Pashchimanchal','Development region',null),
('167','NP','BA','Bagmati','Zone',null),
('167','NP','BH','Bheri','Zone',null),
('167','NP','DH','Dhawalagiri','Zone',null),
('167','NP','GA','Gandaki','Zone',null),
('167','NP','JA','Janakpur','Zone',null),
('167','NP','KA','Karnali','Zone',null),
('167','NP','KO','Kosi [Koshi]','Zone',null),
('167','NP','LU','Lumbini','Zone',null),
('167','NP','MA','Mahakali','Zone',null),
('167','NP','ME','Mechi','Zone',null),
('167','NP','NA','Narayani','Zone',null),
('167','NP','RA','Rapti','Zone',null),
('167','NP','SA','Sagarmatha','Zone',null),
('167','NP','SE','Seti','Zone',null),
('165','NL','DR','Drenthe','Province',null),
('165','NL','FL','Flevoland','Province',null),
('165','NL','FR','Friesland','Province',null),
('165','NL','GE','Gelderland','Province',null),
('165','NL','GR','Groningen','Province',null),
('165','NL','LI','Limburg','Province',null),
('165','NL','NB','Noord-Brabant','Province',null),
('165','NL','NH','Noord-Holland','Province',null),
('165','NL','OV','Overijssel','Province',null),
('165','NL','UT','Utrecht','Province',null),
('165','NL','ZE','Zeeland','Province',null),
('165','NL','ZH','Zuid-Holland','Province',null),
('170','NZ','AUK','Auckland','Regional Council',null),
('170','NZ','BOP','Bay of Plenty','Regional Council',null),
('170','NZ','CAN','Canterbury','Regional Council',null),
('170','NZ','CIT','Chatham Islands Territory','Special Island Authorithy',null),
('170','NZ','GIS','Gisborne District','Unitary Authority',null),
('170','NZ','HKB','Hawkes''s Bay','Regional Council',null),
('170','NZ','MBH','Marlborough District','Unitary Authority',null),
('170','NZ','MWT','Manawatu-Wanganui','Regional Council',null),
('170','NZ','NSN','Nelson City','Unitary Authority',null),
('170','NZ','NTL','Northland','Regional Council',null),
('170','NZ','OTA','Otago','Regional Council',null),
('170','NZ','STL','Southland','Regional Council',null),
('170','NZ','TAS','Tasman District','Unitary Authority',null),
('170','NZ','TKI','Taranaki','Regional Council',null),
('170','NZ','WGN','Wellington','Regional Council',null),
('170','NZ','WKO','Waikato','Regional Council',null),
('170','NZ','WTC','West Coast','Regional Council',null),
('171','OM','BU','Al Buraymī','Governorate',25),
('171','OM','MA','Masqaţ','Governorate',25),
('171','OM','MU','Musandam','Governorate',25),
('171','OM','ZU','Z̧ufār','Governorate',25),
('171','OM','BA','Al Bāţinah','Region',25),
('171','OM','DA','Ad Dākhilīyah','Region',25),
('171','OM','SH','Ash Sharqīyah','Region',25),
('171','OM','WU','Al Wusţá','Region',25),
('171','OM','ZA','Aȥ Ȥāhirah','Region',25),
('177','PK','IS','Islamabad','Federal capital territory',0),
('177','PK','GB','Gilgit-Baltistan','Pakistan administrered area',0),
('177','PK','JK','Azad Kashmir','Pakistan administrered area',0),
('177','PK','BA','Baluchistan','Province',0),
('177','PK','KP','Khyber Pakhtunkhwa','Province',0),
('177','PK','PB','Punjab','Province',0),
('177','PK','SD','Sind','Province',0),
('177','PK','TA','Federally Administered Tribal Areas','Territory',0),
('172','PA','EM','Emberá','Indigenous Region',7),
('172','PA','KY','Kuna Yala','Indigenous Region',7),
('172','PA','NB','Ngöbe-Buglé','Indigenous Region',7),
('172','PA','1','Bocas del Toro','Province',7),
('172','PA','2','Coclé','Province',7),
('172','PA',3,'Colón','Province',7),
('172','PA','4','Chiriquí','Province',7),
('172','PA','5','Darién','Province',7),
('172','PA','6','Herrera','Province',7),
('172','PA','7','Los Santos','Province',7),
('172','PA','8','Panamá','Province',7),
('172','PA','9','Veraguas','Province',7),
('175','PG','NSB','Bougainville','Autonomous Region',10),
('175','PG','NCD','National Capital District (Port Moresby)','District',10),
('175','PG','CPK','Chimbu','Province',10),
('175','PG','CPM','Central','Province',10),
('175','PG','EBR','East New Britain','Province',10),
('175','PG','EHG','Eastern Highlands','Province',10),
('175','PG','EPW','Enga','Province',10),
('175','PG','ESW','East Sepik','Province',10),
('175','PG','GPK','Gulf','Province',10),
('175','PG','MBA','Milne Bay','Province',10),
('175','PG','MPL','Morobe','Province',10),
('175','PG','MPM','Madang','Province',10),
('175','PG','MRL','Manus','Province',10),
('175','PG','NIK','New Ireland','Province',10),
('175','PG','NPP','Northern','Province',10),
('175','PG','SAN','Sandaun (West Sepik)','Province',10),
('175','PG','SHM','Southern Highlands','Province',10),
('175','PG','WBK','West New Britain','Province',10),
('175','PG','WHM','Western Highlands','Province',10),
('175','PG','WPD','Western','Province',10),
('173','PE','CAL','El Callao','Constitutional Province',18),
('173','PE','AMA','Amazonas','Department',18),
('173','PE','ANC','Ancash','Department',18),
('173','PE','APU','Apurímac','Department',18),
('173','PE','ARE','Arequipa','Department',18),
('173','PE','AYA','Ayacucho','Department',18),
('173','PE','CAJ','Cajamarca','Department',18),
('173','PE','CUS','Cuzco [Cusco]','Department',18),
('173','PE','HUC','Huánuco','Department',18),
('173','PE','HUV','Huancavelica','Department',18),
('173','PE','ICA','Ica','Department',18),
('173','PE','JUN','Junín','Department',18),
('173','PE','LAL','La Libertad','Department',18),
('173','PE','LAX','Lambayeque','Department',18),
('173','PE','LIM','Lima','Department',18),
('173','PE','LOR','Loreto','Department',18),
('173','PE','MDD','Madre de Dios','Department',18),
('173','PE','MOQ','Moquegua','Department',18),
('173','PE','PAS','Pasco','Department',18),
('173','PE','PIU','Piura','Department',18),
('173','PE','PUN','Puno','Department',18),
('173','PE','SAM','San Martín','Department',18),
('173','PE','TAC','Tacna','Department',18),
('173','PE','TUM','Tumbes','Department',18),
('173','PE','UCA','Ucayali','Department',18),
('173','PE','LMA','Municipalidad Metropolitana de Lima','Municipality',18),
('176','PH','ABR','Abra','Province',12),
('176','PH','AGN','Agusan del Norte','Province',12),
('176','PH','AGS','Agusan del Sur','Province',12),
('176','PH','AKL','Aklan','Province',12),
('176','PH','ALB','Albay','Province',12),
('176','PH','ANT','Antique','Province',12),
('176','PH','APA','Apayao','Province',12),
('176','PH','AUR','Aurora','Province',12),
('176','PH','BAN','Bataan','Province',12),
('176','PH','BAS','Basilan','Province',12),
('176','PH','BEN','Benguet','Province',12),
('176','PH','BIL','Biliran','Province',12),
('176','PH','BOH','Bohol','Province',12),
('176','PH','BTG','Batangas','Province',12),
('176','PH','BTN','Batanes','Province',12),
('176','PH','BUK','Bukidnon','Province',12),
('176','PH','BUL','Bulacan','Province',12),
('176','PH','CAG','Cagayan','Province',12),
('176','PH','CAM','Camiguin','Province',12),
('176','PH','CAN','Camarines Norte','Province',12),
('176','PH','CAP','Capiz','Province',12),
('176','PH','CAS','Camarines Sur','Province',12),
('176','PH','CAT','Catanduanes','Province',12),
('176','PH','CAV','Cavite','Province',12),
('176','PH','CEB','Cebu','Province',12),
('176','PH','COM','Compostela Valley','Province',12),
('176','PH','DAO','Davao Oriental','Province',12),
('176','PH','DAS','Davao del Sur','Province',12),
('176','PH','DAV','Davao','Province',12),
('176','PH','DIN','Dinagat Islands','Province',12),
('176','PH','EAS','Eastern Samar','Province',12),
('176','PH','GUI','Guimaras','Province',12),
('176','PH','IFU','Ifugao','Province',12),
('176','PH','ILI','Iloilo','Province',12),
('176','PH','ILN','Ilocos Norte','Province',12),
('176','PH','ILS','Ilocoq Sur','Province',12),
('176','PH','ISA','Isabela','Province',12),
('176','PH','KAL','Kalinga-Apayao','Province',12),
('176','PH','LAG','Laguna','Province',12),
('176','PH','LAN','Lanao del Norte','Province',12),
('176','PH','LAS','Lanao del Sur','Province',12),
('176','PH','LEY','Leyte','Province',12),
('176','PH','LUN','La Union','Province',12),
('176','PH','MAD','Marinduque','Province',12),
('176','PH','MAG','Maguindanao','Province',12),
('176','PH','MAS','Masbate','Province',12),
('176','PH','MDC','Mindoro Occidental','Province',12),
('176','PH','MDR','Mindoro Oriental','Province',12),
('176','PH','MOU','Mountain Province','Province',12),
('176','PH','MSC','Misamis Occidental','Province',12),
('176','PH','MSR','Misamis Oriental','Province',12),
('176','PH','NCO','North Cotabato','Province',12),
('176','PH','NEC','Negros occidental','Province',12),
('176','PH','NER','Negros oriental','Province',12),
('176','PH','NSA','Northern Samar','Province',12),
('176','PH','NUE','Nueva Ecija','Province',12),
('176','PH','NUV','Nueva Vizcaya','Province',12),
('176','PH','PAM','Pampanga','Province',12),
('176','PH','PAN','Pangasinan','Province',12),
('176','PH','PLW','Palawan','Province',12),
('176','PH','QUE','Quezon','Province',12),
('176','PH','QUI','Quirino','Province',12),
('176','PH','RIZ','Rizal','Province',12),
('176','PH','ROM','Romblon','Province',12),
('176','PH','SAR','Sarangani','Province',12),
('176','PH','SCO','South Cotabato','Province',12),
('176','PH','SIG','Siquijor','Province',12),
('176','PH','SLE','Southern Leyte','Province',12),
('176','PH','SLU','Sulu','Province',12),
('176','PH','SOR','Sorsogon','Province',12),
('176','PH','SUK','Sultan Kudarat','Province',12),
('176','PH','SUN','Surigao del Norte','Province',12),
('176','PH','SUR','Surigao del Sur','Province',12),
('176','PH','TAR','Tarlac','Province',12),
('176','PH','TAW','Tawi-Tawi','Province',12),
('176','PH','WSA','Western Samar','Province',12),
('176','PH','ZAN','Zamboanga del Norte','Province',12),
('176','PH','ZAS','Zamboanga del Sur','Province',12),
('176','PH','ZMB','Zambales','Province',12),
('176','PH','ZSI','Zamboanga Sibuguey [Zamboanga Sibugay]','Province',12),
('178','PL','DS','Dolnoslaskie','Province',23),
('178','PL','KP','Kujawsko-pomorskie','Province',23),
('178','PL','LB','Lubuskie','Province',23),
('178','PL','LD','Lódzkie','Province',23),
('178','PL','LU','Lubelskie','Province',23),
('178','PL','MA','Malopolskie','Province',23),
('178','PL','MZ','Mazowieckie','Province',23),
('178','PL','OP','Opolskie','Province',23),
('178','PL','PD','Podlaskie','Province',23),
('178','PL','PK','Podkarpackie','Province',23),
('178','PL','PM','Pomorskie','Province',23),
('178','PL','SK','Swietokrzyskie','Province',23),
('178','PL','SL','Slaskie','Province',23),
('178','PL','WN','Warminsko-mazurskie','Province',23),
('178','PL','WP','Wielkopolskie','Province',23),
('178','PL','ZP','Zachodniopomorskie','Province',23),
('186','QA','DA','Ad Dawḩah','Municipality',0),
('186','QA','KH','Al Khawr wa adh Dhakhīrah','Municipality',0),
('186','QA','MS','Ash Shamāl','Municipality',0),
('186','QA','RA','Ar Rayyān','Municipality',0),
('186','QA','US','Umm Şalāl','Municipality',0),
('186','QA','WA','Al Wakrah','Municipality',0),
('186','QA','ZA','Az̧ Z̧a‘āyin','Municipality',0),
('188','RO','AB','Alba','Departments',19),
('188','RO','AG','Argeş','Departments',19),
('188','RO','AR','Arad','Departments',19),
('188','RO','B','Bucureşti','Municipality',19),
('188','RO','BC','Bacău','Departments',19),
('188','RO','BH','Bihor','Departments',19),
('188','RO','BN','Bistriţa-Năsăud','Departments',19),
('188','RO','BR','Brăila','Departments',19),
('188','RO','BT','Botoşani','Departments',19),
('188','RO','BV','Braşov','Departments',19),
('188','RO','BZ','Buzău','Departments',19),
('188','RO','CJ','Cluj','Departments',19),
('188','RO','CL','Călăraşi','Departments',19),
('188','RO','CS','Caraş-Severin','Departments',19),
('188','RO','CT','Constanţa','Departments',19),
('188','RO','CV','Covasna','Departments',19),
('188','RO','DB','Dâmboviţa','Departments',19),
('188','RO','DJ','Dolj','Departments',19),
('188','RO','GJ','Gorj','Departments',19),
('188','RO','GL','Galaţi','Departments',19),
('188','RO','GR','Giurgiu','Departments',19),
('188','RO','HD','Hunedoara','Departments',19),
('188','RO','HR','Harghita','Departments',19),
('188','RO','IF','Ilfov','Departments',19),
('188','RO','IL','Ialomita','Departments',19),
('188','RO','IS','Iaşi','Departments',19),
('188','RO','MH','Mehedinţi','Departments',19),
('188','RO','MM','Maramureş','Departments',19),
('188','RO','MS','Mureş','Departments',19),
('188','RO','NT','Neamţ','Departments',19),
('188','RO','OT','Olt','Departments',19),
('188','RO','PH','Prahova','Departments',19),
('188','RO','SB','Sibiu','Departments',19),
('188','RO','SJ','Sălaj','Departments',19),
('188','RO','SM','Satu Mare','Departments',19),
('188','RO','SV','Suceava','Departments',19),
('188','RO','TL','Tulcea','Departments',19),
('188','RO','TM','Timiş','Departments',19),
('188','RO','TR','Teleorman','Departments',19),
('188','RO','VL','Vâlcea','Departments',19),
('188','RO','VN','Vrancea','Departments',19),
('188','RO','VS','Vaslui','Departments',19),
('190','RU','AMU','Amurskaya oblast''','Administrative region',null),
('190','RU','ARK','Arkhangel''skaya oblast,','Administrative region',null),
('190','RU','AST','Astrakhanskaya oblast''','Administrative region',null),
('190','RU','BEL','Belgorodskaya oblast''','Administrative region',null),
('190','RU','BRY','Bryanskaya oblast''','Administrative region',null),
('190','RU','CHE','Chelyabinskaya oblast''','Administrative region',null),
('190','RU','IRK','Irkutskaya oblast''','Administrative region',null),
('190','RU','IVA','Ivanovskaya oblast''','Administrative region',null),
('190','RU','KEM','Kemerovskaya oblast''','Administrative region',null),
('190','RU','KGD','Kaliningradskaya oblast,','Administrative region',null),
('190','RU','KGN','Kurganskaya oblast''','Administrative region',null),
('190','RU','KIR','Kirovskaya oblast''','Administrative region',null),
('190','RU','KLU','Kaluzhskaya oblast''','Administrative region',null),
('190','RU','KOS','Kostromskaya oblast''','Administrative region',null),
('190','RU','KRS','Kurskaya oblast''','Administrative region',null),
('190','RU','LEN','Leningradskaya oblast''','Administrative region',null),
('190','RU','LIP','Lipetskaya oblast''','Administrative region',null),
('190','RU','MAG','Magadanskaya oblast''','Administrative region',null),
('190','RU','MOS','Moskovskaya oblast''','Administrative region',null),
('190','RU','MUR','Murmanskaya oblast''','Administrative region',null),
('190','RU','NGR','Novgorodskaya oblast''','Administrative region',null),
('190','RU','NIZ','Nizbegorodskaya oblast,','Administrative region',null),
('190','RU','NVS','Novosibirskaya oblast''','Administrative region',null),
('190','RU','OMS','Omskaya oblast''','Administrative region',null),
('190','RU','ORE','Orenburgskaya oblast''','Administrative region',null),
('190','RU','ORL','Orlovskaya oblast''','Administrative region',null),
('190','RU','PNZ','Penzenskaya oblast''','Administrative region',null),
('190','RU','PSK','Pskovskaya oblast''','Administrative region',null),
('190','RU','ROS','Rostovskaya oblast''','Administrative region',null),
('190','RU','RYA','Ryazanskaya oblast''','Administrative region',null),
('190','RU','SAK','Sakhalinskaya oblast''','Administrative region',null),
('190','RU','SAM','Samarskaya oblast''','Administrative region',null),
('190','RU','SAR','Saratovskaya oblast''','Administrative region',null),
('190','RU','SMO','Smolenskaya oblast''','Administrative region',null),
('190','RU','SVE','Sverdlovskaya oblast''','Administrative region',null),
('190','RU','TAM','Tambovskaya oblast''','Administrative region',null),
('190','RU','TOM','Tomskaya oblast''','Administrative region',null),
('190','RU','TUL','Tul''skaya oblast''','Administrative region',null),
('190','RU','TVE','Tverskaya oblast''','Administrative region',null),
('190','RU','TYU','Tyumenskaya oblast''','Administrative region',null),
('190','RU','ULY','Ul''yanovskaya oblast''','Administrative region',null),
('190','RU','VGG','Volgogradskaya oblast''','Administrative region',null),
('190','RU','VLA','Vladimirskaya oblast''','Administrative region',null),
('190','RU','VLG','Vologodskaya oblast''','Administrative region',null),
('190','RU','VOR','Voronezhskaya oblast''','Administrative region',null),
('190','RU','YAR','Yaroslavskaya oblast''','Administrative region',null),
('190','RU','ALT','Altayskiy kray','Administrative territory',null),
('190','RU','KAM','Kamchatskiy kray','Administrative territory',null),
('190','RU','KDA','Krasnodarskiy kray','Administrative territory',null),
('190','RU','KHA','Khabarovskiy kray','Administrative territory',null),
('190','RU','KYA','Krasnoyarskiy kray','Administrative territory',null),
('190','RU','PER','Permskiy kray','Administrative territory',null),
('190','RU','PRI','Primorskiy kray','Administrative territory',null),
('190','RU','STA','Stavropol''skiy kray','Administrative territory',null),
('190','RU','ZAB','Zabaykal''skiy kray','Administrative territory',null),
('190','RU','MOW','Moskva','Autonomous city',null),
('190','RU','SPE','Sankt-Peterburg','Autonomous city',null),
('190','RU','CHU','Chukotskiy avtonomnyy okrug','Autonomous district',null),
('190','RU','KHM','Khanty-Mansiyskiy avtonomnyy okrug-Yugra','Autonomous district',null),
('190','RU','NEN','Nenetskiy avtonomnyy okrug','Autonomous district',null),
('190','RU','YAN','Yamalo-Nenetskiy avtonomnyy okrug','Autonomous district',null),
('190','RU','YEV','Yevreyskaya avtonomnaya oblast''ug','Autonomous region',null),
('205','SO','AW','Awdal','Region',null),
('205','SO','BK','Bakool','Region',null),
('205','SO','BN','Banaadir','Region',null),
('205','SO','BR','Bari','Region',null),
('205','SO','BY','Bay','Region',null),
('205','SO','GA','Galguduud','Region',null),
('205','SO','GE','Gedo','Region',null),
('205','SO','HI','Hiiraan','Region',null),
('205','SO','JD','Jubbada Dhexe','Region',null),
('205','SO','JH','Jubbada Hoose','Region',null),
('205','SO','MU','Mudug','Region',null),
('205','SO','NU','Nugaal','Region',null),
('205','SO','SA','Sanaag','Region',null),
('205','SO','SD','Shabeellaha Dhexe','Region',null),
('205','SO','SH','Shabeellaha Hoose','Region',null),
('205','SO','SO','Sool','Region',null),
('205','SO','TO','Togdheer','Region',null),
('205','SO','WO','Woqooyi Galbeed','Region',null),
('246','ZA','EC','Eastern Cape','Province',null),
('246','ZA','FS','Free State','Province',null),
('246','ZA','GT','Gauteng','Province',null),
('246','ZA','LP','Limpopo','Province',null),
('246','ZA','MP','Mpumalanga','Province',null),
('246','ZA','NC','Northern Cape','Province',null),
('246','ZA','NL','Kwazulu-Natal','Province',null),
('246','ZA','NW','North-West','Province',null),
('246','ZA','WC','Western Cape','Province',null),
('67','ES','A','Alacant','Province',8),
('67','ES','AB','Albacete','Province',8),
('67','ES','AL','Almería','Province',8),
('67','ES','AV','Ávila','Province',8),
('67','ES','B','Barcelona [Barcelona]','Province',8),
('67','ES','BA','Badajoz','Province',8),
('67','ES','BI','Biskaia','Province',8),
('67','ES','BU','Burgos','Province',8),
('67','ES','C','A Coruña [La Coruña]','Province',8),
('67','ES','CA','Cádiz','Province',8),
('67','ES','CC','Cáceres','Province',8),
('67','ES','CE','Ceuta','Autonomous city in North Africa',8),
('67','ES','CO','Córdoba','Province',8),
('67','ES','CR','Ciudad Real','Province',8),
('67','ES','CS','Castelló','Province',8),
('67','ES','CU','Cuenca','Province',8),
('67','ES','GC','Las Palmas','Province',8),
('67','ES','GI','Girona [Gerona]','Province',8),
('67','ES','GR','Granada','Province',8),
('67','ES','GU','Guadalajara','Province',8),
('67','ES','H','Huelva','Province',8),
('67','ES','HU','Huesca','Province',8),
('67','ES','J','Jaén','Province',8),
('67','ES','L','Lleida [Lérida]','Province',8),
('67','ES','LE','León','Province',8),
('67','ES','LO','La Rioja','Province',8),
('67','ES','LU','Lugo [Lugo]','Province',8),
('67','ES','M','Madrid','Province',8),
('67','ES','MA','Málaga','Province',8),
('67','ES','ML','Melilla','Autonomous city in North Africa',8),
('67','ES','MU','Murcia','Province',8),
('67','ES','NA','Nafarroa','Province',8),
('67','ES','O','Asturias','Province',8),
('67','ES','OR','Ourense [Orense]','Province',8),
('67','ES','P','Palencia','Province',8),
('67','ES','PM','Balears [Baleares]','Province',8),
('67','ES','PO','Pontevedra [Pontevedra]','Province',8),
('67','ES','S','Cantabria','Province',8),
('67','ES','SA','Salamanca','Province',8),
('67','ES','SE','Sevilla','Province',8),
('67','ES','SG','Segovia','Province',8),
('67','ES','SO','Soria','Province',8),
('67','ES','SS','Gipuzkoa','Province',8),
('67','ES','T','Tarragona [Tarragona]','Province',8),
('67','ES','TE','Teruel','Province',8),
('67','ES','TF','Santa Cruz de Tenerife','Province',8),
('67','ES','TO','Toledo','Province',8),
('67','ES','V','València','Province',8),
('67','ES','VA','Valladolid','Province',8),
('67','ES','VI','Araba','Province',8),
('67','ES','Z','Zaragoza','Province',8),
('67','ES','ZA','Zamora','Province',8),
('195','SD','DC','Central Darfur','State',null),
('195','SD','DE','East Darfur','State',null),
('195','SD','DN','North Darfur','State',null),
('195','SD','DS','South Darfur','State',null),
('195','SD','DW','West Darfur','State',null),
('195','SD','GD','Gedaref','State',null),
('195','SD','GZ','Gezira','State',null),
('195','SD','KA','Kassala','State',null),
('195','SD','KH','Khartoum','State',null),
('195','SD','KN10','North Kordofan','State',null),
('195','SD','KS','South Kordofan','State',null),
('195','SD','NB','Blue Nile','State',null),
('195','SD','NO','Northern','State',null),
('195','SD','NR','River Nile','State',null),
('195','SD','NW','White Nile','State',null),
('195','SD','RS','Red Sea','State',null),
('195','SD','SI','Sennar','State',null),
('196','SE','AB','Stockholms län[SE-01]','Province',25),
('196','SE','AC','Västerbottens län[SE-24]','Province',25),
('196','SE','BD','Norrbottens län[SE-25]','Province',25),
('196','SE','C','Uppsala län[SE-03]','Province',25),
('196','SE','D','Södermanlands län[SE-04]','Province',25),
('196','SE','E','Östergötlands län[SE-05]','Province',25),
('196','SE','F','Jönköpings län[SE-06]','Province',25),
('196','SE','G','Kronoborgs län[SE-07]','Province',25),
('196','SE','H','Kalmar län[SE-08]','Province',25),
('196','SE','I','Gotlands län[SE-09]','Province',25),
('196','SE','K','Blekinge län[SE-10]','Province',25),
('196','SE','M','Skåne län[SE-12]','Province',25),
('196','SE','N','Hallands län[SE-13]','Province',25),
('196','SE','O','Västra Götalands län[SE-14]','Province',25),
('196','SE','S','Värmlands län[SE-17]','Province',25),
('196','SE','T','Örebro län[SE-18]','Province',25),
('196','SE','U','Västmanlands län[SE-19]','Province',25),
('196','SE','W','Dalarnes län[SE-20]','Province',25),
('196','SE','X','Gävleborgs län[SE-21]','Province',25),
('196','SE','Y','Västernorrlands län[SE-22]','Province',25),
('196','SE','Z','Jämtlands län[SE-23]','Province',25),
('42','CH','AG','Aargau (de)','Canton',7.7),
('42','CH','AI','Appenzell Innerrhoden (de)','Canton',7.7),
('42','CH','AR','Appenzell Ausserrhoden (de)','Canton',7.7),
('42','CH','BE','Bern (de)','Canton',7.7),
('42','CH','BL','Basel-Landschaft (de)','Canton',7.7),
('42','CH','BS','Basel-Stadt (de)','Canton',7.7),
('42','CH','FR','Fribourg (fr)','Canton',7.7),
('42','CH','GE','Genève (fr)','Canton',7.7),
('42','CH','GL','Glarus (de)','Canton',7.7),
('42','CH','GR','Graubünden (de)','Canton',7.7),
('42','CH','JU','Jura (fr)','Canton',7.7),
('42','CH','LU','Luzern (de)','Canton',7.7),
('42','CH','NE','Neuchâtel (fr)','Canton',7.7),
('42','CH','NW','Nidwalden (de)','Canton',7.7),
('42','CH','OW','Obwalden (de)','Canton',7.7),
('42','CH','SG','Sankt Gallen (de)','Canton',7.7),
('42','CH','SH','Schaffhausen (de)','Canton',7.7),
('42','CH','SO','Solothurn (de)','Canton',7.7),
('42','CH','SZ','Schwyz (de)','Canton',7.7),
('42','CH','TG','Thurgau (de)','Canton',7.7),
('42','CH','TI','Ticino (it)','Canton',7.7),
('42','CH','UR','Uri (de)','Canton',7.7),
('42','CH','VD','Vaud (fr)','Canton',7.7),
('42','CH','VS','Valais (fr)','Canton',7.7),
('42','CH','ZG','Zug (de)','Canton',7.7),
('42','CH','ZH','Zürich (de)','Canton',7.7),
('227','TW','CHA','Changhua','District',5),
('227','TW','CYQ','Chiayi','District',5),
('227','TW','HSZQ','Hsinchu','District',5),
('227','TW','HUA','Hualien','District',5),
('227','TW','ILA','Ilan','District',5),
('227','TW','KHQ','Kaohsiung','District',5),
('227','TW','MIA','Miaoli','District',5),
('227','TW','NAN','Nantou','District',5),
('227','TW','PEN','Penghu','District',5),
('227','TW','PIF','Pingtung','District',5),
('227','TW','TAO','Taoyuan','District',5),
('227','TW','TNQ','Tainan','District',5),
('227','TW','TPQ','Taipei','District',5),
('227','TW','TTT','Taitung','District',5),
('227','TW','TXQ','Taichung','District',5),
('227','TW','YUN','Yunlin','District',5),
('227','TW','CYI','Chiayi','Municipality',5),
('227','TW','HSZ','Hsinchu','Municipality',5),
('227','TW','KEE','Keelung','Municipality',5),
('227','TW','TNN','Tainan','Municipality',5),
('227','TW','TXG','Taichung','Municipality',5),
('227','TW','KHH','Kaohsiung','Special Municipality',5),
('227','TW','TPE','Taipei','Special Municipality',5),
('218','TJ','GB','Gorno-Badakhshan','Autonomous Region',null),
('218','TJ','KT','Khatlon','Region',null),
('218','TJ','SU','Sughd','Region',null),
('2','AE','AJ','Ajman','Emirate',5),
('2','AE','AZ','Abū Ȥaby[Abu Dhabi]','Emirate',5),
('2','AE','DU','Dubayy [Dubai]','Emirate',5),
('2','AE','FU','Al Fujayrah','Emirate',5),
('2','AE','RK','Rā''s al Khaymah','Emirate',5),
('2','AE','SH','Ash Shāriqah [Sharjah]','Emirate',5),
('2','AE','UQ','Umm al Qaywayn','Emirate',5),
('76','GB','ABD','Aberdeenshire','Council area',19.87),
('76','GB','ABE','Aberdeen City','Council area',19.87),
('76','GB','AGB','Argyll and Bute','Council area',19.87),
('76','GB','AGY','Isle of Anglesey [Sir Ynys Môn GB-YNM]','Unitary authority',19.87),
('76','GB','ANS','Angus','Council area',19.87),
('76','GB','ANT','Antrim','District council area',19.87),
('76','GB','ARD','Ards','District council area',19.87),
('76','GB','ARM','Armagh','District council area',19.87),
('76','GB','BAS','Bath and North East Somerset','Unitary authority',19.87),
('76','GB','BBD','Blackburn with Darwen','Unitary authority',19.87),
('76','GB','BDF','Bedfordshire','Unitary authority',19.87),
('76','GB','BDG','Barking and Dagenham','London borough',19.87),
('76','GB','BEN','Brent','London borough',19.87),
('76','GB','BEX','Bexley','London borough',19.87),
('76','GB','BFS','Belfast','District council area',19.87),
('76','GB','BGE','Bridgend [Pen-y-bont ar Ogwr GB-POG]','Unitary authority',19.87),
('76','GB','BGW','Blaenau Gwent','Unitary authority',19.87),
('76','GB','BIR','Birmingham','Metropolitan district',19.87),
('76','GB','BKM','Buckinghamshire','Two-tier county',19.87),
('76','GB','BLA','Ballymena','District council area',19.87),
('76','GB','BLY','Ballymoney','District council area',19.87),
('76','GB','BMH','Bournemouth','Unitary authority',19.87),
('76','GB','BNB','Banbridge','District council area',19.87),
('76','GB','BNE','Barnet','London borough',19.87),
('76','GB','BNH','Brighton and Hove','Unitary authority',19.87),
('76','GB','BNS','Barnsley','Metropolitan district',19.87),
('76','GB','BOL','Bolton','Metropolitan district',19.87),
('76','GB','BPL','Blackpool','Unitary authority',19.87),
('76','GB','BRC','Bracknell Forest','Unitary authority',19.87),
('76','GB','BRD','Bradford','Metropolitan district',19.87),
('76','GB','BRY','Bromley','London borough',19.87),
('76','GB','BST','Bristol, City of','Unitary authority',19.87),
('76','GB','BUR','Bury','Metropolitan district',19.87),
('76','GB','CAM','Cambridgeshire','Two-tier county',19.87),
('76','GB','CAY','Caerphilly [Caerffili GB-CAF]','Unitary authority',19.87),
('76','GB','CBF','Central Bedfordshire','Unitary authority',19.87),
('76','GB','CGN','Ceredigion [Sir Ceredigion]','Unitary authority',19.87),
('76','GB','CGV','Craigavon','District council area',19.87),
('76','GB','CHE','Cheshire East','Unitary authority',19.87),
('76','GB','CHW','Cheshire West and Chester','Unitary authority',19.87),
('76','GB','CKF','Carrickfergus','District council area',19.87),
('76','GB','CKT','Cookstown','District council area',19.87),
('76','GB','CLD','Calderdale','Metropolitan district',19.87),
('76','GB','CLK','Clackmannanshire','Council area',19.87),
('76','GB','CLR','Coleraine','District council area',19.87),
('76','GB','CMA','Cumbria','Two-tier county',19.87),
('76','GB','CMD','Camden','London borough',19.87),
('76','GB','CMN','Carmarthenshire [Sir Gaerfyrddin GB-GFY]','Unitary authority',19.87),
('76','GB','CON','Cornwall','Unitary authority',19.87),
('76','GB','COV','Coventry','Metropolitan district',19.87),
('76','GB','CRF','Cardiff [Caerdydd GB-CRD]','Unitary authority',19.87),
('76','GB','CRY','Croydon','London borough',19.87),
('76','GB','CSR','Castlereagh','District council area',19.87),
('76','GB','CWY','Conwy','Unitary authority',19.87),
('76','GB','DAL','Darlington','Unitary authority',19.87),
('76','GB','DBY','Derbyshire','Two-tier county',19.87),
('76','GB','DEN','Denbighshire [Sir Ddinbych GB-DDB]','Unitary authority',19.87),
('76','GB','DER','Derby','Unitary authority',19.87),
('76','GB','DEV','Devon','Two-tier county',19.87),
('76','GB','DGN','Dungannon','District council area',19.87),
('76','GB','DGY','Dumfries and Galloway','Council area',19.87),
('76','GB','DNC','Doncaster','Metropolitan district',19.87),
('76','GB','DND','Dundee City','Council area',19.87),
('76','GB','DOR','Dorset','Two-tier county',19.87),
('76','GB','DOW','Down','District council area',19.87),
('76','GB','DRY','Derry','District council area',19.87),
('76','GB','DUD','Dudley','Metropolitan district',19.87),
('76','GB','DUR','Durham','Unitary authority',19.87),
('76','GB','EAL','Ealing','London borough',19.87),
('76','GB','EAY','East Ayrshire','Council area',19.87),
('76','GB','EDH','Edinburgh, City of','Council area',19.87),
('76','GB','EDU','East Dunbartonshire','Council area',19.87),
('76','GB','ELN','East Lothian','Council area',19.87),
('76','GB','ELS','Eilean Siar','Council area',19.87),
('76','GB','ENF','Enfield','London borough',19.87),
('76','GB','ERW','East Renfrewshire','Council area',19.87),
('76','GB','ERY','East Riding of Yorkshire','Unitary authority',19.87),
('76','GB','ESS','Essex','Two-tier county',19.87),
('76','GB','ESX','East Sussex','Two-tier county',19.87),
('76','GB','FAL','Falkirk','Council area',19.87),
('76','GB','FER','Fermanagh','District council area',19.87),
('76','GB','FIF','Fife','Council area',19.87),
('76','GB','FLN','Flintshire [Sir y Fflint GB-FFL]','Unitary authority',19.87),
('76','GB','GAT','Gateshead','Metropolitan district',19.87),
('76','GB','GLG','Glasgow City','Council area',19.87),
('76','GB','GLS','Gloucestershire','Two-tier county',19.87),
('76','GB','GRE','Greenwich','London borough',19.87),
('76','GB','GWN','Gwynedd','Unitary authority',19.87),
('76','GB','HAL','Halton','Unitary authority',19.87),
('76','GB','HAM','Hampshire','Two-tier county',19.87),
('76','GB','HAV','Havering','London borough',19.87),
('76','GB','HCK','Hackney','London borough',19.87),
('76','GB','HEF','Herefordshire, County of','Unitary authority',19.87),
('76','GB','HIL','Hillingdon','London borough',19.87),
('76','GB','HLD','Highland','Council area',19.87),
('76','GB','HMF','Hammersmith and Fulham','London borough',19.87),
('76','GB','HNS','Hounslow','London borough',19.87),
('76','GB','HPL','Hartlepool','Unitary authority',19.87),
('76','GB','HRT','Hertfordshire','Two-tier county',19.87),
('76','GB','HRW','Harrow','London borough',19.87),
('76','GB','HRY','Haringey','London borough',19.87),
('76','GB','IOW','Isle of Wight','Unitary authority',19.87),
('76','GB','ISL','Islington','London borough',19.87),
('76','GB','IVC','Inverclyde','Council area',19.87),
('76','GB','KEC','Kensington and Chelsea','London borough',19.87),
('76','GB','KEN','Kent','Two-tier county',19.87),
('76','GB','KHL','Kingston upon Hull, City of','Unitary authority',19.87),
('76','GB','KIR','Kirklees','Metropolitan district',19.87),
('76','GB','KTT','Kingston upon Thames','London borough',19.87),
('76','GB','KWL','Knowsley','Metropolitan districtn',19.87),
('76','GB','LAN','Lancashire','Two-tier county',19.87),
('76','GB','LBH','Lambeth','London borough',19.87),
('76','GB','LCE','Leicester','Unitary authority',19.87),
('76','GB','LDS','Leeds','Metropolitan district',19.87),
('76','GB','LEC','Leicestershire','Two-tier county',19.87),
('76','GB','LEW','Lewisham','London borough',19.87),
('76','GB','LIN','Lincolnshire','Two-tier county',19.87),
('76','GB','LIV','Liverpool','Metropolitan district',19.87),
('76','GB','LMV','Limavady','District council area',19.87),
('76','GB','LND','London, City of','City Corporation',19.87),
('76','GB','LRN','Larne','District council area',19.87),
('76','GB','LSB','Lisburn','District council area',19.87),
('76','GB','LUT','Luton','Unitary authority',19.87),
('76','GB','MAN','Manchester','Metropolitan district',19.87),
('76','GB','MDB','Middlesbrough','Unitary authority',19.87),
('76','GB','MDW','Medway','Unitary authority',19.87),
('76','GB','MFT','Magherafelt','District council area',19.87),
('76','GB','MIK','Milton Keynes','Unitary authority',19.87),
('76','GB','MLN','Midlothian','Council area',19.87),
('76','GB','MON','Monmouthshire [Sir Fynwy GB-FYN]','Unitary authority',19.87),
('76','GB','MRT','Merton','London borough',19.87),
('76','GB','MRY','Moray','Council area',19.87),
('76','GB','MTY','Merthyr Tydfil [Merthyr Tudful GB-MTU]','Unitary authority',19.87),
('76','GB','MYL','Moyle','District council area',19.87),
('76','GB','NAY','North Ayrshire','Council area',19.87),
('76','GB','NBL','Northumberland','Unitary authority',19.87),
('76','GB','NDN','North Down','District council area',19.87),
('76','GB','NEL','North East Lincolnshire','Unitary authority',19.87),
('76','GB','NET','Newcastle upon Tyne','Metropolitan district',19.87),
('76','GB','NFK','Norfolk','Two-tier county',19.87),
('76','GB','NGM','Nottingham','Unitary authority',19.87),
('76','GB','NLK','North Lanarkshire','Council area',19.87),
('76','GB','NLN','North Lincolnshire','Unitary authority',19.87),
('76','GB','NSM','North Somerset','Unitary authority',19.87),
('76','GB','NTA','Newtownabbey','District council area',19.87),
('76','GB','NTH','Northamptonshire','Two-tier county',19.87),
('76','GB','NTL','Neath Port Talbot [Castell-nedd Port Talbot GB-CTL]','Unitary authority',19.87),
('76','GB','NTT','Nottinghamshire','Two-tier county',19.87),
('76','GB','NTY','North Tyneside','Metropolitan district',19.87),
('76','GB','NWM','Newham','London borough',19.87),
('76','GB','NWP','Newport [Casnewydd GB-CNW]','Unitary authority',19.87),
('76','GB','NYK','North Yorkshire','Two-tier county',19.87),
('76','GB','NYM','Newry and Mourne','District council area',19.87),
('76','GB','OLD','Oldham','Metropolitan district',19.87),
('76','GB','OMH','Omagh','District council area',19.87),
('76','GB','ORK','Orkney Islands','Council area',19.87),
('76','GB','OXF','Oxfordshire','Two-tier county',19.87),
('76','GB','PEM','Pembrokeshire [Sir Benfro GB-BNF]','Unitary authority',19.87),
('76','GB','PKN','Perth and Kinross','Council area',19.87),
('76','GB','PLY','Plymouth','Unitary authority',19.87),
('76','GB','POL','Poole','Unitary authority',19.87),
('76','GB','POR','Portsmouth','Unitary authority',19.87),
('76','GB','POW','Powys','Unitary authority',19.87),
('76','GB','PTE','Peterborough','Unitary authority',19.87),
('76','GB','RCC','Redcar and Cleveland','Unitary authority',19.87),
('76','GB','RCH','Rochdale','Metropolitan district',19.87),
('76','GB','RCT','Rhondda, Cynon, Taff [Rhondda, Cynon,Taf]','Unitary authority',19.87),
('76','GB','RDB','Redbridge','London borough',19.87),
('76','GB','RDG','Reading','Unitary authority',19.87),
('76','GB','RFW','Renfrewshire','Council area',19.87),
('76','GB','RIC','Richmond upon Thames','London borough',19.87),
('76','GB','ROT','Rotherham','Metropolitan district',19.87),
('76','GB','RUT','Rutland','Unitary authority',19.87),
('76','GB','SAW','Sandwell','Metropolitan district',19.87),
('76','GB','SAY','South Ayrshire','Council area',19.87),
('76','GB','SCB','Scottish Borders, The','Council area',19.87),
('76','GB','SFK','Suffolk','Two-tier county',19.87),
('76','GB','SFT','Sefton','Metropolitan district',19.87),
('76','GB','SGC','South Gloucestershire','Unitary authority',19.87),
('76','GB','SHF','Sheffield','Metropolitan district',19.87),
('76','GB','SHN','St. Helens','Metropolitan district',19.87),
('76','GB','SHR','Shropshire','Unitary authority',19.87),
('76','GB','SKP','Stockport','Metropolitan district',19.87),
('76','GB','SLF','Salford','Metropolitan district',19.87),
('76','GB','SLG','Slough','Unitary authority',19.87),
('76','GB','SLK','South Lanarkshire','Council area',19.87),
('76','GB','SND','Sunderland','Metropolitan district',19.87),
('76','GB','SOL','Solihull','Metropolitan district',19.87),
('76','GB','SOM','Somerset','Two-tier county',19.87),
('76','GB','SOS','Southend-on-Sea','Unitary authority',19.87),
('76','GB','SRY','Surrey','Two-tier county',19.87),
('76','GB','STB','Strabane','District council area',19.87),
('76','GB','STE','Stoke-on-Trent','Unitary authority',19.87),
('76','GB','STG','Stirling','Council area',19.87),
('76','GB','STH','Southampton','Unitary authority',19.87),
('76','GB','STN','Sutton','London borough',19.87),
('76','GB','STS','Staffordshire','Two-tier county',19.87),
('76','GB','STT','Stockton-on-Tees','Unitary authority',19.87),
('76','GB','STY','South Tyneside','Metropolitan district',19.87),
('76','GB','SWA','Swansea [Abertawe GB-ATA]','Unitary authority',19.87),
('76','GB','SWD','Swindon','Unitary authority',19.87),
('76','GB','SWK','Southwark','London borough',19.87),
('76','GB','TAM','Tameside','Metropolitan district',19.87),
('76','GB','TFW','Telford and Wrekin','Unitary authority',19.87),
('76','GB','THR','Thurrock','Unitary authority',19.87),
('76','GB','TOB','Torbay','Unitary authorityn',19.87),
('76','GB','TOF','Torfaen [Tor-faen]','Unitary authority',19.87),
('76','GB','TRF','Trafford','Metropolitan district',19.87),
('76','GB','TWH','Tower Hamlets','London borough',19.87),
('76','GB','VGL','Vale of Glamorgan, The [Bro Morgannwg GB-BMG]','Unitary authority',19.87),
('76','GB','WAR','Warwickshire','Two-tier county',19.87),
('76','GB','WBK','West Berkshire','Unitary authority',19.87),
('76','GB','WDU','West Dunbartonshire','Council area',19.87),
('76','GB','WFT','Waltham Forest','London borough',19.87),
('76','GB','WGN','Wigan','Metropolitan district',19.87),
('76','GB','WIL','Wiltshire','Unitary authority',19.87),
('76','GB','WKF','Wakefield','Metropolitan district',19.87),
('76','GB','WLL','Walsall','Metropolitan district',19.87),
('76','GB','WLN','West Lothian','Council area',19.87),
('76','GB','WLV','Wolverhampton','Metropolitan district',19.87),
('76','GB','WND','Wandsworth','London borough',19.87),
('76','GB','WNM','Windsor and Maidenhead','Unitary authority',19.87),
('76','GB','WOK','Wokingham','Unitary authority',19.87),
('76','GB','WOR','Worcestershire','Two-tier county',19.87),
('76','GB','WRL','Wirral','Metropolitan district',19.87),
('76','GB','WRT','Warrington','Unitary authority',19.87),
('76','GB','WRX','Wrexham [Wrecsam GB-WRC]','Unitary authority',19.87),
('76','GB','WSM','Westminster','London borough',19.87),
('76','GB','WSX','West Sussex','Two-tier county',19.87),
('76','GB','YOR','York','Unitary authority',19.87),
('76','GB','ZET','Shetland Islands','Council area',19.87),
('232','US','AK','Alaska','State',null),
('232','US','AL','Alabama','State',null),
('232','US','AR','Arkansas','State',null),
('232','US','AS','American Samoa (see also separate entry under AS)','Outlying area',null),
('232','US','AZ','Arizona','State',null),
('232','US','CA','California','State',null),
('232','US','CO','Colorado','State',null),
('232','US','CT','Connecticut','State',null),
('232','US','DC','District of Columbia','District',null),
('232','US','DE','Delaware','State',null),
('232','US','FL','Florida','State',null),
('232','US','GA','Georgia','State',null),
('232','US','GU','Guam (see also separate entry under GU)','Outlying area',null),
('232','US','HI','Hawaii','State',null),
('232','US','IA','Iowa','State',null),
('232','US','ID','Idaho','State',null),
('232','US','IL','Illinois','State',null),
('232','US','IN','Indiana','State',null),
('232','US','KS','Kansas','State',null),
('232','US','KY','Kentucky','State',null),
('232','US','LA','Louisiana','State',null),
('232','US','MA','Massachusetts','State',null),
('232','US','MD','Maryland','State',null),
('232','US','ME','Maine','State',null),
('232','US','MI','Michigan','State',null),
('232','US','MN','Minnesota','State',null),
('232','US','MO','Missouri','State',null),
('232','US','MP','Northern Mariana Islands (see also separate entry MP)','Outlying area',null),
('232','US','MS','Mississippi','State',null),
('232','US','MT','Montana','State',null),
('232','US','NC','North Carolina','State',null),
('232','US','ND','North Dakota','State',null),
('232','US','NE','Nebraska','State',null),
('232','US','NH','New Hampshire','State',null),
('232','US','NJ','New Jersey','State',null),
('232','US','NM','New Mexico','State',null),
('232','US','NV','Nevada','State',null),
('232','US','NY','New York','State',null),
('232','US','OH','Ohio','State',null),
('232','US','OK','Oklahoma','State',null),
('232','US','OR','Oregon','State',null),
('232','US','PA','Pennsylvania','State',null),
('232','US','PR','Puerto Rico (see also separate entry under PR)','Outlying area',null),
('232','US','RI','Rhode Island','State',null),
('232','US','SC','South Carolina','State',null),
('232','US','SD','South Dakota','State',null),
('232','US','TN','Tennessee','State',null),
('232','US','TX','Texas','State',null),
('232','US','UM','U.S. Minor Outlying Islands (cf. separate entry UM)','Outlying area',null),
('232','US','UT','Utah','State',null),
('232','US','VA','Virginia','State',null),
('232','US','VI','Virgin Islands of the U.S. (see also separate entry VI)','Outlying area',null),
('232','US','VT','Vermont','State',null),
('232','US','WA','Washington','State',null),
('232','US','WI','Wisconsin','State',null),
('232','US','WV','West Virginia','State',null),
('232','US','WY','Wyoming','State',null),
('233','UY','AR','Artigas','Department',22),
('233','UY','CA','Canelones','Department',22),
('233','UY','CL','Cerro Largo','Department',22),
('233','UY','CO','Colonia','Department',22),
('233','UY','DU','Durazno','Department',22),
('233','UY','FD','Florida','Department',22),
('233','UY','FS','Flores','Department',22),
('233','UY','LA','Lavalleja','Department',22),
('233','UY','MA','Maldonado','Department',22),
('233','UY','MO','Montevideo','Department',22),
('233','UY','PA','Paysandú','Department',22),
('233','UY','RN','Río Negro','Department',22),
('233','UY','RO','Rocha','Department',22),
('233','UY','RV','Rivera','Department',22),
('233','UY','SA','Salto','Department',22),
('233','UY','SJ','San José','Department',22),
('233','UY','SO','Soriano','Department',22),
('233','UY','TA','Tacuarembó','Department',22),
('233','UY','TT','Treinta y Tres','Department',22),
('234','UZ','AN','Andijon','Region',null),
('234','UZ','BU','Bukhoro','Region',null),
('234','UZ','FA','Farghona','Region',null),
('234','UZ','JI','Jizzakh','Region',null),
('234','UZ','KH','Khorazm','Region',null),
('234','UZ','NG','Namangan','Region',null),
('234','UZ','NW','Nawoiy','Region',null),
('234','UZ','QA','Qashqadaryo','Region',null),
('234','UZ','QR','Qoraqalpoghiston Respublikasi','Republic',null),
('234','UZ','SA','Samarqand','Region',null),
('234','UZ','SI','Sirdaryo','Region',null),
('234','UZ','SU','Surkhondaryo','Region',null),
('234','UZ','TK','Toshkent','City',null),
('234','UZ','TO','Toshkent','Region',null),
('234','UZ','XO','Xorazm','Region',null),
('237','VE','A','Distrito Capital','Capital District',16),
('237','VE','B','Anzoátegui','State',16),
('237','VE','C','Apure','State',16),
('237','VE','D','Aragua','State',16),
('237','VE','E','Barinas','State',16),
('237','VE','F','Bolívar','State',16),
('237','VE','G','Carabobo','State',16),
('237','VE','H','Cojedes','State',16),
('237','VE','I','Falcón','State',16),
('237','VE','J','Guárico','State',16),
('237','VE','K','Lara','State',16),
('237','VE','L','Mérida','State',16),
('237','VE','M','Miranda','State',16),
('237','VE','N','Monagas','State',16),
('237','VE','O','Nueva Esparta','State',16),
('237','VE','P','Portuguesa','State',16),
('237','VE','R','Sucre','State',16),
('237','VE','S','Táchira','State',16),
('237','VE','T','Trujillo','State',16),
('237','VE','U','Yaracuy','State',16),
('237','VE','V','Zulia','State',16),
('237','VE','W','Dependencias Federales','Federal Dependencies',16),
('237','VE','X','vargas','State',16),
('237','VE','Y','Delta Amacuro','State',16),
('237','VE','Z','Amazonas','State',16),
('240','VN','CT','Can Tho','Municipality',10),
('240','VN','DN','Da Nang','Municipality',10),
('240','VN','HN','Ha Noi','Municipality',10),
('240','VN','HP','Hai Phong','Municipality',10),
('240','VN','SG','Ho Chi Minh','Municipality',10),
('240','VN','1','Lai Chau','Province',10),
('240','VN','2','Lao Cai','Province',10),
('240','VN',3,'Ha Giang','Province',10),
('240','VN','4','Cao Bang','Province',10),
('240','VN','5','Son La','Province',10),
('240','VN','6','Yen Bai','Province',10),
('240','VN','7','Tuyen Quang','Province',10),
('240','VN','8','Lang Son','Province',10),
('240','VN','9','Quang Ninh','Province',10),
('240','VN',10,'Hoa Binh','Province',10),
('240','VN','11','Ha Tay','Province',10),
('240','VN','12','Ninh Binh','Province',10),
('240','VN','13','Thai Binh','Province',10),
('240','VN','14','Thanh Hoa','Province',10),
('240','VN','15','Nghe An','Province',10),
('240','VN','16','Ha Tinh','Province',10),
('240','VN','17','Quang Binh','Province',10),
('240','VN','18','Quang Tri','Province',10),
('240','VN','19','Thua Thien-Hue','Province',10),
('240','VN','20','Quang Nam','Province',10),
('240','VN','21','Kon Tum','Province',10),
('240','VN','22','Quang Ngai','Province',10),
('240','VN','23','Gia Lai','Province',10),
('240','VN','24','Binh Dinh','Province',10),
('240','VN','25','Phu Yen','Province',10),
('240','VN','26','Dac Lac','Province',10),
('240','VN','27','Khanh Hoa','Province',10),
('240','VN','28','Lam Dong','Province',10),
('240','VN','29','Ninh Thuan','Province',10),
('240','VN','30','Tay Ninh','Province',10),
('240','VN','31','Dong Nai','Province',10),
('240','VN','32','Binh Thuan','Province',10),
('240','VN','33','Long An','Province',10),
('240','VN','34','Ba Ria - Vung Tau','Province',10),
('240','VN','35','An Giang','Province',10),
('240','VN','36','Dong Thap','Province',10),
('240','VN','37','Tien Giang','Province',10),
('240','VN','38','Kien Giang','Province',10),
('240','VN','39','Vinh Long','Province',10),
('240','VN','40','Ben Tre','Province',10),
('240','VN','41','Tra Vinh','Province',10),
('240','VN','42','Soc Trang','Province',10),
('240','VN','43','Bac Can','Province',10),
('240','VN','44','Bac Giang','Province',10),
('240','VN','45','Bac Lieu','Province',10),
('240','VN','46','Bac Ninh','Province',10),
('240','VN','47','Binh Duong','Province',10),
('240','VN','48','Binh Phuoc','Province',10),
('240','VN','49','Ca Mau','Province',10),
('240','VN','50','Da Nang', null,10),
('240','VN','50','thanh pho',null,10),
('240','VN','51','Hai Duong','Province',10),
('240','VN','52','Hai Phong', null,10),
('240','VN','52','thanh pho', null,10),
('240','VN','53','Ha Nam','Province',10),
('240','VN','54','Hung Yen','Province',10),
('240','VN','55','Nam Dinh','Province',10),
('240','VN','56','Phu Tho','Province',10),
('240','VN','57','Thai Nguyen','Province',10),
('240','VN','58','Vinh Yen','Province',10),
('240','VN','59','Dien Bien','Province',10),
('240','VN','60','Dak Nong','Province',10),
('240','VN','61','Hau Giang','Province',10),
('244','YE','AB','Abyan','Governorate',5),
('244','YE','AD','Adan','Governorate',5),
('244','YE','AM','Amrān','Governorate',5),
('244','YE','BA','Al Bayḑā''','Governorate',5),
('244','YE','DA','Aḑ Ḑāli''','Governorate',5),
('244','YE','DH','Dhamār','Governorate',5),
('244','YE','HD','Ḩaḑramawt','Governorate',5),
('244','YE','HJ','Ḩajjah','Governorate',5),
('244','YE','HU','Al Ḩudaydah','Governorate',5),
('244','YE','IB','Ibb','Governorate',5),
('244','YE','JA','Al Jawf','Governorate',5),
('244','YE','LA','Laḩij','Governorate',5),
('244','YE','MA','Ma''rib','Governorate',5),
('244','YE','MR','Al Mahrah','Governorate',5),
('244','YE','MW','Al Maḩwīt','Governorate',5),
('244','YE','RA','Raymah','Governorate',5),
('244','YE','SD','Şāʻdah','Governorate',5),
('244','YE','SH','Shabwah','Governorate',5),
('244','YE','SN','Şanʻā''','Governorate',5),
('244','YE','TA','Tāʻizz','Governorate',5),
('244','YE','SA','Şanʻā'' [city]','Municipality',5),
('248','ZW','BU','Bulawayo','Province',14.5),
('248','ZW','HA','Harare','Province',14.5),
('248','ZW','MA','Manicaland','Province',14.5),
('248','ZW','MC','Mashonaland Central','Province',14.5),
('248','ZW','ME','Mashonaland East','Province',14.5),
('248','ZW','MI','Midlands','Province',14.5),
('248','ZW','MN','Matabeleland North','Province',14.5),
('248','ZW','MS','Matabeleland South','Province',14.5),
('248','ZW','MV','Masvingo','Province',14.5),
('248','ZW','MW','Mashonaland West','Province',14.5);
